# Generated by Django 4.2 on 2024-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='layout',
            field=models.CharField(choices=[('block', 'block'), ('grid', 'grid'), ('d-flex', 'flex')], default='block', max_length=6),
        ),
    ]
