# Generated by Django 4.2 on 2024-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_block_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_container',
            field=models.BooleanField(default=True),
        ),
    ]
