# Generated by Django 4.2 on 2024-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_block_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='element',
            field=models.CharField(choices=[('section', 'section'), ('div', 'div')], default='div', max_length=9),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
