# Generated by Django 4.2 on 2024-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_alter_block_element_alter_block_is_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Bloco'},
        ),
        migrations.AlterField(
            model_name='block',
            name='element',
            field=models.CharField(choices=[('section', 'Seção'), ('div', 'Conteúdo')], default='div', help_text='Escolha a estrutura do bloco', max_length=9, verbose_name='Tipo de elemento'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='block',
            name='layout',
            field=models.CharField(choices=[('block', 'Caixa'), ('grid', 'Em grade'), ('d-flex', 'Flexível')], default='block', help_text='Defina como o conteúdo será disposto', max_length=6, verbose_name='Layout'),
        ),
    ]
