# Generated by Django 4.2 on 2024-05-10 20:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blocks', '0005_alter_block_options_alter_block_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem de fundo'),
        ),
    ]
