# Generated by Django 4.2 on 2024-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_block_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='background_size',
            field=models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover'), ('initial', 'Initial')], default='contain', max_length=8),
        ),
    ]
