# Generated by Django 4.2 on 2024-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_block_background_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='background_size',
            field=models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover'), ('initial', 'Initial')], default='cover', max_length=8),
        ),
    ]
