# Generated by Django 3.2 on 2024-01-11 22:18

from django.db import migrations, models
import django.db.models.deletion
import nossas.design.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0002_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_column', serialize=False, to='cms.cmsplugin')),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('col', models.CharField(choices=[('', 'Auto'), ('g-col-1', 'Col 1'), ('g-col-2', 'Col 2'), ('g-col-3', 'Col 3'), ('g-col-4', 'Col 4'), ('g-col-5', 'Col 5'), ('g-col-6', 'Col 6'), ('g-col-7', 'Col 7'), ('g-col-8', 'Col 8'), ('g-col-9', 'Col 9'), ('g-col-10', 'Col 10'), ('g-col-11', 'Col 11'), ('g-col-12', 'Col 12')], default='', help_text='Defina manualmente o número de colunas que esta coluna ocupará.', max_length=15, verbose_name='Coluna')),
                ('rows', models.CharField(choices=[('', 'Auto'), ('grid-row: 2', 'Linha 2'), ('grid-row: 3', 'Linha 3'), ('grid-row: 4', 'Linha 4')], default='', help_text='Escolha manualmente o número da linha que esta coluna ocupará.', max_length=15, verbose_name='Linhas')),
                ('col_start_at', models.CharField(choices=[('', 'Auto'), ('g-start-1', 'Start at Col 1'), ('g-start-2', 'Start at Col 2'), ('g-start-3', 'Start at Col 3'), ('g-start-4', 'Start at Col 4'), ('g-start-5', 'Start at Col 5'), ('g-start-6', 'Start at Col 6'), ('g-start-7', 'Start at Col 7'), ('g-start-8', 'Start at Col 8'), ('g-start-9', 'Start at Col 9'), ('g-start-10', 'Start at Col 10'), ('g-start-11', 'Start at Col 11'), ('g-start-12', 'Start at Col 12')], default='', help_text='Defina em qual coluna o elemento deve iniciar.', max_length=30, verbose_name='Alinhamento horizontal da coluna')),
            ],
            options={
                'abstract': False,
            },
            bases=(nossas.design.models.UIBackgroundMixin, 'cms.cmsplugin'),
        ),
        migrations.AddField(
            model_name='grid',
            name='grid_gap',
            field=models.CharField(choices=[('row-gap: 0;', 'Sem espaçamento'), ('row-gap: 4;', 'Pequeno'), ('row-gap: 8;', 'Grande')], default='row-gap: 0;', help_text='Selecione o espaço entre colunas do Grid.', max_length=15, verbose_name='Espaçamento do Grid'),
        ),
        migrations.AddField(
            model_name='grid',
            name='grid_layout',
            field=models.CharField(choices=[('', 'Auto'), ('g-col-12', '1 Coluna'), ('g-col-12 g-col-md-6', '2 Colunas'), ('g-col-12 g-col-md-4', '3 Colunas'), ('g-col-12 g-col-sm-2 g-col-4', '4 Colunas'), ('g-col-12 g-col-sm-2 g-col-2', '6 Colunas'), ('g-col-12 g-col-sm-2 g-col-1', '12 Colunas')], default='', help_text="Escolha 'Auto' para um layout responsivo automático ou para selecionar o número de colunas manualmente.", max_length=80, verbose_name='Layout do Grid'),
        ),
    ]
