# Generated by Django 3.2 on 2024-01-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0007_auto_20240116_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_accordion', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(verbose_name='Título')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
