# Generated by Django 3.2 on 2024-01-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0013_auto_20240124_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_headline', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(verbose_name='Título')),
                ('icon', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
