# Generated by Django 3.2 on 2024-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='icon',
            field=models.CharField(blank=True, choices=[('icon-rosa.svg', 'Rosa'), ('icon-azul.svg', 'Azul'), ('icon-amarelo.svg', 'Amarelo'), ('icon-laranja.svg', 'Laranja'), ('icon-verde.svg', 'Verde'), ('icon-vermelho.svg', 'Vermelho')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Título'),
        ),
    ]
