# Generated by Django 3.2 on 2024-01-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_header_picture'),
        ('plugins', '0015_auto_20240129_1747'),
    ]

    operations = [
    ]
