# Generated by Django 3.2 on 2024-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0018_header_graphic_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='picture',
        ),
        migrations.AlterField(
            model_name='header',
            name='graphic_element',
            field=models.CharField(blank=True, choices=[('questionador', 'Questionador'), ('hub', 'Hub, Eixo'), ('impacto', 'Impacto'), ('empatico', 'Empático')], max_length=120, null=True, verbose_name='Elemento gráfico'),
        ),
    ]
