# Generated by Django 3.2 on 2024-01-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('plugins', '0019_auto_20240131_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_headerimage', serialize=False, to='cms.cmsplugin')),
                ('graphic_icon', models.CharField(blank=True, choices=[('questionador', 'Questionador'), ('hub', 'Hub, Eixo'), ('impulsionador', 'Impulsionador')], max_length=50, null=True, verbose_name='Ícone gráfico')),
                ('picture', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem de Fundo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
