# Generated by Django 3.2 on 2024-02-01 14:16

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('plugins', '0022_breadcrumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='card',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag'),
        ),
    ]
