# Generated by Django 3.2 on 2024-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0023_auto_20240201_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='fluid',
            field=models.BooleanField(default=False, help_text='Permite o conteúdo interno avançar os limites padrões da página', verbose_name='Conteúdo fluído'),
        ),
    ]
