# Generated by Django 3.2 on 2024-02-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0025_alter_breadcrumb_graphic_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSharePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_socialsharepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
