# Generated by Django 3.2 on 2024-02-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0026_socialsharepluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsharepluginmodel',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
