# Generated by Django 3.2 on 2024-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0027_socialsharepluginmodel_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsharepluginmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='socialsharepluginmodel',
            name='selected_social_media',
            field=models.CharField(blank=True, max_length=255, verbose_name='Redes Sociais Selecionadas'),
        ),
    ]
