# Generated by Django 3.2 on 2024-03-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0029_auto_20240208_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='external_link',
            field=models.CharField(blank=True, help_text='Provide a link to an external source.', max_length=2040, verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='card',
            name='internal_link',
            field=models.ForeignKey(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Internal link'),
        ),
        migrations.AddField(
            model_name='card',
            name='target',
            field=models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Target'),
        ),
    ]
