# Generated by Django 3.2 on 2024-02-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0029_auto_20240221_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsharepluginmodel',
            name='title',
        ),
    ]
