# Generated by Django 3.2 on 2024-03-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0029_auto_20240208_2051'),
        ('plugins', '0030_remove_socialsharepluginmodel_title'),
    ]

    operations = [
    ]
