# Generated by Django 4.2 on 2024-03-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0030_auto_20240304_1636'),
        ('plugins', '0031_merge_20240304_1408'),
    ]

    operations = [
    ]
