# Generated by Django 3.2 on 2023-07-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da ação')),
                ('slug', models.SlugField(help_text='Deve ser único para cada ação, usado para agrupar seus dados', unique=True, verbose_name='Slug')),
                ('settings', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivistAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('family_name', models.CharField(blank=True, max_length=105, null=True, verbose_name='Sobrenome')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Endereço de e-mail')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número de telefone')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('origin_uid', models.PositiveIntegerField(verbose_name='ID da ação')),
                ('origin_name', models.SlugField(max_length=100, verbose_name='Origem da ação')),
                ('origin_action_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da ação')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
            ],
        ),
        migrations.AddIndex(
            model_name='activistaction',
            index=models.Index(fields=['origin_name', 'origin_action_date'], name='actions_act_origin__cad5e2_idx'),
        ),
    ]
