# Generated by Django 3.2 on 2023-07-13 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20230711_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da ação')),
                ('slug', models.SlugField(help_text='Deve ser único para cada ação, usado para agrupar seus dados', unique=True, verbose_name='Slug')),
                ('settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'campanha',
            },
        ),
        migrations.RemoveField(
            model_name='activistaction',
            name='action',
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'ação', 'verbose_name_plural': 'ações'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'grupo'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='owner_group',
        ),
        migrations.RemoveField(
            model_name='action',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='action',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='action',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='action',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='action',
            name='email_address',
            field=models.EmailField(default='', max_length=254, verbose_name='Endereço de e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='family_name',
            field=models.CharField(blank=True, max_length=105, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='action',
            name='given_name',
            field=models.CharField(default='', max_length=50, verbose_name='Primeiro nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='origin_action_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da ação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='origin_name',
            field=models.CharField(choices=[('table:activist_pressures', 'Tabela ação de ativistas'), ('app:super_pressure', 'App de superpressão'), ('upload:csv', 'Upload de arquivo CSV'), ('app:lunda_donation', 'Doação pelo Lunda'), ('app:cms_pressure_email', 'Pressão pelo CMS')], default='', max_length=100, verbose_name='Origem da ação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='origin_uid',
            field=models.PositiveIntegerField(default=1, verbose_name='ID da ação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Número de telefone'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['origin_name', 'origin_action_date'], name='actions_act_origin__5962b2_idx'),
        ),
        migrations.DeleteModel(
            name='ActivistAction',
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.group'),
        ),
        migrations.AddField(
            model_name='action',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actions.campaign'),
            preserve_default=False,
        ),
    ]
