# Generated by Django 3.2 on 2023-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20230713_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='reference_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Objeto de referência'),
        ),
    ]
