# Generated by Django 3.2 on 2023-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_group_reference_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('done', 'Finalizada')], default='draft', max_length=50),
        ),
    ]
