# Generated by Django 3.2 on 2023-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_action_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
    ]
