# Generated by Django 4.2 on 2024-07-08 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunhando'), ('submitted', 'Enviado'), ('invalid', 'Inválido'), ('is_valid', 'Validado'), ('draft_requested', 'Edição Requisitada')], default='draft', max_length=50)),
                ('validations', models.JSONField(blank=True)),
                ('candidature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidature.candidature')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CandidatureState',
        ),
    ]
