# Generated by Django 4.2 on 2024-07-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0005_alter_candidatureflow_candidature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'verbose_name': 'Candidatura'},
        ),
        migrations.AlterModelOptions(
            name='candidatureflow',
            options={'verbose_name': 'Formulário'},
        ),
        migrations.AddField(
            model_name='candidature',
            name='milestones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='social_media',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
