# Generated by Django 4.2 on 2024-07-22 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0005_alter_candidatureflow_candidature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'verbose_name': 'Candidatura'},
        ),
        migrations.AlterModelOptions(
            name='candidatureflow',
            options={'verbose_name': 'Formulário'},
        ),
        migrations.AddField(
            model_name='candidature',
            name='milestones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=140), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='candidature',
            name='social_media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, null=True, size=5),
        ),
    ]
