# Generated by Django 4.2 on 2024-07-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0006_alter_candidature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='color',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('indígena', 'Indígena'), ('parda', 'Parda'), ('não declarada', 'Não declarada')], default='branca', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='education',
            field=models.CharField(choices=[('le_e_escreve', 'Lê e escreve'), ('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('não superior_incompleto', 'Ensino Superior Incompleto'), ('superior_completo', 'Ensino Superior Completo')], default='le_e_escreve', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='gender',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], default='homem', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='intended_position',
            field=models.CharField(choices=[('prefeitura', 'Prefeitura'), ('vice_prefeitura', 'Vice-Prefeitura'), ('vereadore', 'Vereador(a)')], default='prefeitura', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='political_party',
            field=models.CharField(choices=[('mdb', 'MDB'), ('pdt', 'PDT'), ('pt', 'PT'), ('pcdob', 'PCdoB'), ('psb', 'PSB'), ('psdb', 'PSDB'), ('agir', 'AGIR'), ('mobiliza', 'MOBILIZA'), ('cidadania', 'CIDADANIA'), ('pv', 'PV'), ('avante', 'AVANTE'), ('pstu', 'PSTU'), ('pcb', 'PCB'), ('prtb', 'PRTB'), ('dc', 'DC'), ('pco', 'PCO'), ('pode', 'PODE'), ('republicanos', 'REPUBLICANOS'), ('psol', 'PSOL'), ('psd', 'PSD'), ('solidariedade', 'SOLIDARIEDADE'), ('novo', 'NOVO'), ('rede', 'REDE'), ('pmb', 'PMB'), ('up', 'UP'), ('uniao', 'UNIÃO'), ('prd', 'PRD')], default='mdb', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='sexuality',
            field=models.CharField(blank=True, choices=[('Heterossexual', 'Heterossexual'), ('Pansexual', 'Pansexual'), ('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Queer', 'Queer'), ('Gay', 'Gay'), ('Lésbica', 'Lesbica'), ('Não declarada', 'No Answer')], default='Heterossexual', max_length=30, null=True),
        ),
    ]
