# Generated by Django 4.2 on 2024-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_alter_candidature_photo_alter_candidature_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
