# Generated by Django 4.2 on 2024-07-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_rename_cpf_cnpj_candidature_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatureflow',
            name='photo',
            field=models.ImageField(null=True, upload_to='tmp/photos/'),
        ),
        migrations.AddField(
            model_name='candidatureflow',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tmp/videos/'),
        ),
    ]
