# Generated by Django 4.2 on 2024-08-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0008_candidature_slug'),
        ('candidature', '0008_candidatureflow_cropping_candidatureflow_photo_and_more'),
    ]

    operations = [
    ]
