# Generated by Django 4.2 on 2024-08-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_alter_candidature_photo_alter_candidature_video'),
        ('candidature', '0008_candidatureflow_cropping_candidatureflow_photo_and_more'),
    ]

    operations = [
    ]
