# Generated by Django 4.2 on 2024-08-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0009_merge_20240813_1734'),
        ('candidature', '0009_merge_20240813_2137'),
    ]

    operations = [
    ]
