# Generated by Django 4.2 on 2024-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0010_merge_20240816_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='flags',
            new_name='proposes',
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='photo',
            field=models.ImageField(null=True, upload_to='candidatures/photos/'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviado'), ('invalid', 'Inválido'), ('is_valid', 'Válido'), ('draft_requested', 'Edição Requisitada')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/videos/'),
        ),
    ]
