# Generated by Django 4.2 on 2024-08-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0010_merge_20240815_1251'),
        ('candidature', '0011_rename_flags_candidature_proposes_and_more'),
    ]

    operations = [
    ]
