# Generated by Django 4.2 on 2024-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0012_merge_20240816_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='deputy_mayor',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Cadastro Incompleto'), ('editing', 'Em edição'), ('submitted', 'Enviado'), ('invalid', 'Inválido'), ('is_valid', 'Válido')], default='draft', max_length=50),
        ),
    ]
