# Generated by Django 4.2 on 2024-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0013_candidature_deputy_mayor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='deputy_mayor_political_party',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
