# Generated by Django 4.2 on 2024-08-30 15:12

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidature', '0014_candidature_deputy_mayor_political_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='appointments',
            field=models.JSONField(blank=True, verbose_name='Compromissos'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='ballot_name',
            field=models.CharField(max_length=100, verbose_name='Nome na Urna'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='city',
            field=models.CharField(max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cpf',
            field=models.CharField(max_length=30, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='deputy_mayor',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Vice-prefeito'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='deputy_mayor_political_party',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Partido do Vice-prefeito'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='education',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma opção'), ('ensino_fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('ensino_fundamental_completo', 'Ensino Fundamental Completo'), ('ensino_medio_incompleto', 'Ensino Médio Incompleto'), ('ensino_medio_completo', 'Ensino Médio Completo'), ('tecnico_incompleto', 'Técnico Incompleto'), ('tecnico_completo', 'Técnico Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao_incompleta', 'Pós-Graduação Incompleta'), ('pos_graduacao_completa', 'Pós-Graduação Completa'), ('mestrado_incompleto', 'Mestrado Incompleto'), ('mestrado_completo', 'Mestrado Completo'), ('doutorado_incompleto', 'Doutorado Incompleto'), ('doutorado_completo', 'Doutorado Completo')], max_length=80, null=True, verbose_name='Educação'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='employment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='intended_position',
            field=models.CharField(choices=[('', 'Selecione uma opção'), ('prefeitura', 'Prefeitura'), ('vereacao', 'Vereação')], max_length=50, verbose_name='Cargo Pretendido'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='is_collective_mandate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Mandato Coletivo'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='legal_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='milestones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Marcos'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='number_id',
            field=models.PositiveIntegerField(verbose_name='Número na Urna'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='political_party',
            field=models.CharField(choices=[('', 'Selecione o partido'), ('pdt', 'PDT'), ('novo', 'Novo'), ('psdb', 'PSDB'), ('rede', 'Rede'), ('mdb', 'MDB'), ('ptb', 'PTB'), ('pt', 'PT'), ('união', 'União'), ('pcdob', 'PCdoB'), ('psb', 'PSB'), ('ptc', 'PTC'), ('psc', 'PSC'), ('pmn', 'PMN'), ('cidadania', 'Cidadania'), ('pv', 'PV'), ('avante', 'Avante'), ('pp', 'PP'), ('pstu', 'PSTU'), ('pcb', 'PCB'), ('prtb', 'PRTB'), ('dc', 'DC'), ('pco', 'PCO'), ('pode', 'PODE'), ('republicanos', 'Republicanos'), ('psol', 'PSOL'), ('pl', 'PL'), ('psd', 'PSD'), ('patriota', 'Patriota'), ('pros', 'PROS'), ('solidariedade', 'Solidariedade'), ('pmb', 'PMB'), ('up', 'UP')], max_length=60, verbose_name='Partido Político'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='proposes',
            field=models.JSONField(blank=True, verbose_name='Propostas'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='sexuality',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma opção'), ('heterossexual', 'Heterossexual'), ('pansexual', 'Pansexual'), ('assexual', 'Assexual'), ('bissexual', 'Bissexual'), ('queer', 'Queer'), ('gay', 'Gay'), ('lesbica', 'Lésbica'), ('nao_declarada', 'Não declarada')], max_length=30, null=True, verbose_name='Sexualidade'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='short_description',
            field=models.TextField(verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='social_media',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Redes Sociais'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='state',
            field=models.CharField(max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/videos/', verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='candidature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidature.candidature', verbose_name='Candidatura'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='photo',
            field=models.ImageField(null=True, upload_to='candidatures/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='properties',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Propriedades'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Cadastro Incompleto'), ('editing', 'Edição Incompleta'), ('submitted', 'Perfil em análise'), ('invalid', 'Perfil Reprovado'), ('is_valid', 'Perfil Ativo')], default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='validations',
            field=models.JSONField(blank=True, null=True, verbose_name='Validações'),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/videos/', verbose_name='Vídeo'),
        ),
    ]
