# Generated by Django 4.2 on 2024-09-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0016_alter_candidature_options_candidature_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Candidatura'},
        ),
    ]
