# Generated by Django 4.2 on 2024-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0019_alter_candidature_intended_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='sexuality',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma opção'), ('heterossexual', 'Heterossexual'), ('pansexual', 'Pansexual'), ('bissexual', 'Bissexual'), ('gay', 'Homossexual'), ('queer', 'Queer'), ('lesbica', 'Lésbica'), ('nao_declarada', 'Não declarada')], max_length=30, null=True, verbose_name='Sexualidade'),
        ),
    ]
