# Generated by Django 4.2 on 2024-09-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0020_alter_candidature_sexuality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='political_party',
            field=models.CharField(choices=[('', 'Selecione o partido'), ('agir', 'Agir'), ('avante', 'Avante'), ('cidadania', 'Cidadania'), ('dc', 'DC'), ('mdb', 'MDB'), ('mobiliza', 'Mobiliza'), ('novo', 'Novo'), ('patriota', 'Patriota'), ('pcb', 'PCB'), ('pcdob', 'PCdoB'), ('pco', 'PCO'), ('pdt', 'PDT'), ('pl', 'PL'), ('pmb', 'PMB'), ('pmn', 'PMN'), ('pode', 'PODE'), ('pp', 'PP'), ('prd', 'PRD'), ('pros', 'PROS'), ('prtb', 'PRTB'), ('psb', 'PSB'), ('psc', 'PSC'), ('psd', 'PSD'), ('psdb', 'PSDB'), ('psol', 'PSOL'), ('pstu', 'PSTU'), ('pt', 'PT'), ('ptb', 'PTB'), ('ptc', 'PTC'), ('pv', 'PV'), ('rede', 'Rede'), ('republicanos', 'Republicanos'), ('solidariedade', 'Solidariedade'), ('união', 'União'), ('up', 'UP')], max_length=60, verbose_name='Partido Político'),
        ),
    ]
