# Generated by Django 4.2 on 2024-09-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0021_alter_candidature_political_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='ballot_name',
            field=models.CharField(max_length=100, verbose_name='Nome na urna'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Cor ou raça'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='deputy_mayor_political_party',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Partido do vice-prefeito'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='intended_position',
            field=models.CharField(choices=[('', 'Selecione uma opção'), ('prefeitura', 'Prefeito/a'), ('vereacao', 'Vereador/a')], max_length=50, verbose_name='Cargo pretendido'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='is_collective_mandate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Mandato coletivo'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='number_id',
            field=models.PositiveIntegerField(verbose_name='Número na urna'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='political_party',
            field=models.CharField(choices=[('', 'Selecione o partido'), ('agir', 'Agir'), ('avante', 'Avante'), ('cidadania', 'Cidadania'), ('dc', 'DC'), ('mdb', 'MDB'), ('mobiliza', 'Mobiliza'), ('novo', 'Novo'), ('patriota', 'Patriota'), ('pcb', 'PCB'), ('pcdob', 'PCdoB'), ('pco', 'PCO'), ('pdt', 'PDT'), ('pl', 'PL'), ('pmb', 'PMB'), ('pmn', 'PMN'), ('pode', 'PODE'), ('pp', 'PP'), ('prd', 'PRD'), ('pros', 'PROS'), ('prtb', 'PRTB'), ('psb', 'PSB'), ('psc', 'PSC'), ('psd', 'PSD'), ('psdb', 'PSDB'), ('psol', 'PSOL'), ('pstu', 'PSTU'), ('pt', 'PT'), ('ptb', 'PTB'), ('ptc', 'PTC'), ('pv', 'PV'), ('rede', 'Rede'), ('republicanos', 'Republicanos'), ('solidariedade', 'Solidariedade'), ('união', 'União'), ('up', 'UP')], max_length=60, verbose_name='Partido político'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='sexuality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sexualidade'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='short_description',
            field=models.TextField(verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='social_media',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Redes sociais'),
        ),
    ]
