# Generated by Django 4.2 on 2024-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0022_alter_candidature_ballot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='election_status',
            field=models.CharField(blank=True, choices=[('eleita', 'Eleita/o'), ('segundo_turno', 'Segundo Turno'), ('nao_eleito', 'Não Eleita/o')], max_length=20, null=True, verbose_name='Status da Eleição'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='election_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano da Eleição'),
        ),
    ]
