# Generated by Django 4.2 on 2024-10-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0022_alter_candidature_ballot_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('eleita', 'Eleita/o'), ('segundo_turno', 'Segundo Turno'), ('nao_eleito', 'Não Eleita/o')], max_length=20, verbose_name='Status da eleição')),
            ],
        ),
        migrations.AddField(
            model_name='candidature',
            name='election_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano da eleição'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('cpf', 'election_year'), name='unique_cpf_per_year'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='candidature.candidature'),
        ),
    ]
