# Generated by Django 3.2 on 2023-08-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('eleicao', '0002_alter_candidate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleicaoCarousel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='eleicao_eleicaocarousel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
