# Generated by Django 3.2 on 2023-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0007_auto_20230821_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=30, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_trans',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Se identifica como pessoa transgênero/transexual?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('indígena', 'Indígena'), ('parda', 'Parda'), ('não declarada', 'Não declarada')], max_length=30, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='eleicaocarousel',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eleicaocarousel',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
