# Generated by Django 3.2 on 2023-08-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0008_auto_20230822_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='lgpd',
            field=models.BooleanField(default=False, verbose_name='Aviso de Privacidade'),
        ),
    ]
