# Generated by Django 3.2 on 2023-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0009_auto_20230822_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicaocarousel',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição'),
        ),
    ]
