# Generated by Django 3.2 on 2023-08-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0012_auto_20230825_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='pollingplace',
            options={'verbose_name': 'Local de Votação', 'verbose_name_plural': 'Locais de Votação'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'Eleitor(a)', 'verbose_name_plural': 'Eleitores'},
        ),
        migrations.AddField(
            model_name='voter',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.pollingplace'),
        ),
    ]
