# Generated by Django 3.2 on 2023-08-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0013_auto_20230830_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Quero receber atualizações da campanha e do NOSSAS.'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade onde você vota*'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.pollingplace', verbose_name='Local de votação'),
        ),
    ]
