# Generated by Django 3.2 on 2023-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0015_auto_20230831_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Quero receber atualizações da campanha e do NOSSAS.'),
        ),
    ]
