# Generated by Django 3.2 on 2023-09-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('eleicao', '0016_alter_voter_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterFormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='eleicao_voterformpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='Descubra candidatas(os) para você!', max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('button_text', models.CharField(blank=True, default='Quero descobrir', max_length=100, null=True, verbose_name='Texto do botão')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
