# Generated by Django 4.2 on 2024-03-28 16:14

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_slug_alter_publication_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link externo'),
        ),
    ]
