# Generated by Django 3.2 on 2023-07-19 15:33

import contrib.actions.fields
import contrib.actions.pressure.models.targets
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', contrib.actions.fields.CampaignField(blank=True, choices=[(6, 'Concurso sem preconceito -(concurso-sem-preconceito)')], null=True)),
            ],
            options={
                'verbose_name': 'pressão',
                'verbose_name_plural': 'pressões',
            },
        ),
        migrations.CreateModel(
            name='PressurePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pressure_pressurepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('reference_id', models.IntegerField(blank=True, help_text='ID de referência da widget na plataforma Bonde', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TwitterPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Tweet')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure.pressure')),
            ],
            options={
                'verbose_name': 'twitter',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome do alvo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('publish_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'alvo',
            },
            managers=[
                ('on_site', contrib.actions.pressure.models.targets.CustomCurrentSiteManager('publish_on')),
            ],
        ),
        migrations.AddField(
            model_name='pressure',
            name='targets',
            field=models.ManyToManyField(blank=True, to='pressure.Target'),
        ),
        migrations.CreateModel(
            name='PhonePressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField(verbose_name='Roteiro da ligação')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure.pressure')),
            ],
            options={
                'verbose_name': 'telefone',
            },
        ),
        migrations.CreateModel(
            name='EmailPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.CharField(max_length=120, verbose_name='E-mail para resposta')),
                ('subject', models.CharField(max_length=120, verbose_name='Assunto do e-mail')),
                ('body', models.TextField(verbose_name='Corpo do e-mail')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure.pressure')),
            ],
            options={
                'verbose_name': 'email',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email_address', 'Endereço de e-mail'), ('phone_number', 'Número de telefone'), ('twitter', 'Twitter'), ('invalid', 'Outra opção')], max_length=20, verbose_name='Tipo do contato')),
                ('name', models.CharField(blank=True, help_text='Ex. Gabinete 01', max_length=100, null=True, verbose_name='Nome do contato')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure.target')),
            ],
            options={
                'verbose_name': 'contato',
                'unique_together': {('kind', 'value')},
            },
        ),
    ]
