# Generated by Django 3.2 on 2023-07-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurepluginmodel',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pressure.pressure'),
            preserve_default=False,
        ),
    ]
