# Generated by Django 3.2 on 2023-07-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0002_pressurepluginmodel_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailpressure',
            old_name='plugin',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='phonepressure',
            old_name='plugin',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='twitterpressure',
            old_name='plugin',
            new_name='action',
        ),
    ]
