# Generated by Django 3.2 on 2023-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0003_auto_20230724_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailpressure',
            old_name='action',
            new_name='plugin',
        ),
        migrations.RenameField(
            model_name='phonepressure',
            old_name='action',
            new_name='plugin',
        ),
        migrations.RenameField(
            model_name='twitterpressure',
            old_name='action',
            new_name='plugin',
        ),
    ]
