# Build staticfiles
FROM node:18-alpine AS node-builder

WORKDIR /app

COPY . .

WORKDIR /app/tailwind

RUN npm i

RUN npm run page:build

RUN npm run admin:build

# Python runtime based on Debian Bookworm
FROM python:3.10-slim-bookworm

EXPOSE 8000

ENV PYTHONUNBUFFERED=1 \
    PORT=8000 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Install system packages required by Django CMS and Django.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cargo \
        libssl-dev \
        libffi-dev \
        sox \
        ffmpeg \
        libcairo2 \
        libcairo2-dev \
        python3-dev \
        git \
    && rm -rf /var/lib/apt/lists/*

# Install the application server.
RUN python -m pip install --upgrade pip setuptools wheel && \
    pip install uwsgi django-storages boto3 django-prometheus

# Install the project requirements.
COPY org_nossas/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

WORKDIR /app

COPY --from=node-builder /app ./

RUN python manage.py collectstatic --noinput --clear -i tailwindcss

ENV ENABLE_CHECK_TRAEFIK=True

CMD ["uwsgi", "--ini", "/app/wsgi.ini"]
