# Generated by Django 3.2 on 2023-10-05 12:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='lineColor',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Cor da borda'),
        ),
        migrations.AddField(
            model_name='maps',
            name='pointA',
            field=models.FileField(blank=True, null=True, upload_to='maps/icons/'),
        ),
        migrations.AddField(
            model_name='maps',
            name='pointB',
            field=models.FileField(blank=True, null=True, upload_to='maps/icons/'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='geojson',
            field=models.FileField(blank=True, null=True, upload_to='maps/geojson/'),
        ),
    ]
