# Generated by Django 3.2 on 2023-10-05 13:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20231005_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='pointB',
            new_name='point_a',
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='pointA',
            new_name='point_b',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='lineColor',
        ),
        migrations.AddField(
            model_name='maps',
            name='line_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Cor da linha'),
        ),
    ]
