# Generated by Django 3.2 on 2023-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20231005_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='search_placeholder',
            field=models.CharField(blank=True, max_length=80, verbose_name='Placeholder do Campo de Busca'),
        ),
    ]
