# Generated by Django 3.2 on 2024-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleguidemodel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome dos Plugins'),
        ),
    ]
