# Generated by Django 3.2 on 2024-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleguidemodel',
            name='css_classes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Classes CSS'),
        ),
        migrations.AlterField(
            model_name='styleguidemodel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome dos Plugins'),
        ),
    ]
