# Generated by Django 3.2 on 2023-06-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA',
            fields=[
                ('uuid', models.CharField(blank=True, help_text='Ex. G-XXXXXXXXXX', max_length=15, null=True, verbose_name='ID de métricas')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
            ],
        ),
    ]
