# Generated by Django 3.2 on 2023-06-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='grid_column', serialize=False, to='cms.cmsplugin')),
                ('align', models.CharField(choices=[('justify-items-center', 'Centro'), ('justify-items-left', 'Esquerda'), ('justify-items-right', 'Direita')], default='justify-items-center', max_length=30, verbose_name='Alinhamento')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='grid_grid', serialize=False, to='cms.cmsplugin')),
                ('cols', models.CharField(choices=[('grid-cols-1', '1 Coluna'), ('grid-cols-1 md:grid-cols-2', '2 Colunas'), ('grid-cols-1 md:grid-cols-3', '3 Colunas'), ('grid-cols-1 sm:grid-cols-2 md:grid-cols-4', '4 Colunas'), ('grid-cols-1 md:grid-cols-[1fr_2fr]', '2 colunas, 4 x 8')], default='grid-cols-1', max_length=80, verbose_name='Colunas')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
