# Generated by Django 3.2 on 2023-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20230613_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='alignment_x',
            field=models.CharField(choices=[('items-center', 'Centro'), ('items-start', 'Esquerda'), ('items-end', 'Direita')], default='items-center', max_length=30, verbose_name='Alinhamento Horizontal'),
        ),
    ]
