# Generated by Django 3.2 on 2023-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_column_alignment_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='spacing',
            field=models.CharField(choices=[('gap-0', 'Sem espaçamento'), ('gap_4', 'Pequeno'), ('gap_8', 'Grande')], default='gap-0', help_text='Espaço entre os elementos desta Coluna', max_length=15, verbose_name='Espaçamento'),
        ),
    ]
