# Generated by Django 3.2 on 2023-06-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('grid', '0005_alter_column_spacing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidGrid',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='grid_fluidgrid', serialize=False, to='cms.cmsplugin')),
                ('cols', models.CharField(choices=[('grid-cols-2 md:grid-cols-4', '4 Colunas'), ('grid-cols-2 md:grid-cols-6', '6 Colunas')], default='grid-cols-2 md:grid-cols-4', max_length=50, verbose_name='Colunas')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
