# Generated by Django 3.2 on 2024-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalinformation',
            name='contact_phone',
            field=models.CharField(max_length=16, verbose_name='Telefone de contato'),
        ),
        migrations.AlterField(
            model_name='institutionalinformation',
            name='zipcode',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
