# Generated by Django 3.2 on 2024-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_auto_20240111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalinformation',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
    ]
