# Generated by Django 4.2 on 2024-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooltip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltip',
            name='direction',
            field=models.CharField(blank=True, choices=[('', 'Esquerda'), ('right', 'Direita')], max_length=30, null=True, verbose_name='Direção'),
        ),
        migrations.AlterField(
            model_name='tooltip',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
    ]
