# Generated by Django 3.2 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_column_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='classnames',
        ),
        migrations.RemoveField(
            model_name='row',
            name='classnames',
        ),
        migrations.AddField(
            model_name='column',
            name='styled',
            field=models.CharField(choices=[('auto', 'Auto')], default='auto', max_length=20, verbose_name='Estilho da coluna'),
        ),
        migrations.AddField(
            model_name='row',
            name='styled',
            field=models.CharField(choices=[('flex', 'Flex')], default='flex', max_length=20, verbose_name='Estilo da linha'),
        ),
    ]
