# Generated by Django 3.2 on 2023-05-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20230519_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbutton',
            name='bg_color',
            field=models.CharField(blank=True, default='blue', max_length=100, verbose_name='cor do fundo'),
        ),
        migrations.AlterField(
            model_name='row',
            name='styled',
            field=models.CharField(choices=[('flex', 'Flex'), ('wrap', 'Wrap')], default='flex', max_length=20, verbose_name='Estilo da linha'),
        ),
    ]
