# Generated by Django 3.2 on 2023-06-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20230605_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do alvo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do alvo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do alvo')),
            ],
        ),
        migrations.AddField(
            model_name='pressure',
            name='disable_editing',
            field=models.BooleanField(default=True, verbose_name='Desabilitar edição do e-mail e do assunto pelos ativistas?'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='email_body',
            field=models.TextField(default='', verbose_name='Corpo do e-mail de agradecimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='email_subject',
            field=models.CharField(default='', max_length=120, verbose_name='Assunto do e-mail de agradecimento para quem vai pressionar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='sender_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email de resposta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='sender_name',
            field=models.CharField(default='', max_length=120, verbose_name='Remetente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='sharing',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], default='', max_length=50, verbose_name='Opções de compartilhamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='submissions_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intervalo de envio'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='submissions_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Limite de envios únicos'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='whatsapp_text',
            field=models.TextField(default='', verbose_name='Mensagem para o whatsapp'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do grupo')),
                ('email_subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='Assunto do e-mail para os alvos')),
                ('email_body', models.TextField(blank=True, null=True, verbose_name='Corpo do e-mail para os alvos')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.pressure')),
                ('targets', models.ManyToManyField(to='campaign.Target')),
            ],
        ),
    ]
