# Generated by Django 3.2 on 2023-06-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20230605_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetgroup',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='targetgroup',
            name='email_subject',
        ),
    ]
