# Generated by Django 3.2 on 2023-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20230607_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Alvo', 'verbose_name_plural': 'Alvos'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'verbose_name': 'Grupo de alvos', 'verbose_name_plural': 'Grupos de alvos'},
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='email_body',
            new_name='thank_email_body',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='email_subject',
            new_name='thank_email_subject',
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='targets',
            field=models.ManyToManyField(to='campaign.Target', verbose_name='Alvos'),
        ),
    ]
