# Generated by Django 3.2 on 2023-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20230607_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressure',
            name='email_body',
            field=models.TextField(default='', verbose_name='Corpo do e-mail para os alvos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='email_subject',
            field=models.JSONField(default='', verbose_name='Assunto do e-mail para os alvos'),
            preserve_default=False,
        ),
    ]
