# Generated by Django 3.2 on 2023-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20230607_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure',
            name='sharing',
            field=models.JSONField(verbose_name='Opções de compartilhamento'),
        ),
    ]
