# Generated by Django 3.2 on 2023-06-21 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('campaign', '0015_faviconextension'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaviconExtension',
            new_name='IconExtension',
        ),
    ]
