# Generated by Django 3.2 on 2023-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20230626_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure',
            name='targets',
            field=models.JSONField(blank=True, null=True, verbose_name='Alvos'),
        ),
    ]
