# Generated by Django 3.2 on 2023-06-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_alter_pressure_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressure',
            name='disable_editing',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='sharing',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='submissions_interval',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='submissions_limit',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='thank_email_body',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='thank_email_subject',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='whatsapp_text',
        ),
    ]
