# Generated by Django 3.2 on 2023-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondewidgets_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_name',
            field=models.CharField(max_length=255, verbose_name='Custom Field Name'),
        ),
    ]
