# Generated by Django 3.2 on 2023-03-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('bondewidgets_forms', '0002_auto_20230314_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field_name', 'cmsplugin_ptr')},
        ),
    ]
