# Generated by Django 3.2 on 2023-03-30 02:10

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='landpage_content', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'ordering': ('position',),
            },
            bases=('cms.cmsplugin',),
        ),
    ]
