# Generated by Django 3.2 on 2023-03-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(choices=[('background-color', 'Background Color'), ('background', 'Background')], max_length=30, verbose_name='property')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_item', to='landpage.content')),
            ],
        ),
    ]
