# Generated by Django 3.2 on 2023-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_auto_20230330_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_menu',
            field=models.BooleanField(default=True, verbose_name='render menu'),
        ),
    ]
