# Generated by Django 3.2 on 2023-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0003_content_is_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='value',
            field=models.CharField(max_length=150, verbose_name='value'),
        ),
    ]
