# Generated by Django 3.2 on 2024-01-26 16:58

from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('apps', '0002_delete_campaignlistpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da vaga')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Descrição da vaga')),
                ('workload', models.CharField(max_length=50, verbose_name='Carga horária')),
                ('condition', models.CharField(max_length=50, verbose_name='Condições de trabalho')),
                ('responsibilities', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Responsabilidades da vaga')),
                ('prerequisites', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Pré-requisitos da vaga')),
                ('benefits', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Benefícios')),
                ('salary_estimate', models.CharField(max_length=80, verbose_name='Estimativa salarial')),
                ('status', models.CharField(choices=[('opened', 'Aberto'), ('closed', 'Fechado')], default='opened', max_length=20, verbose_name='Status da vaga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('picture', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
