# Generated by Django 3.2 on 2024-01-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('apps', '0005_member_membergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Colaborador'},
        ),
        migrations.AlterModelOptions(
            name='membergroup',
            options={'verbose_name': 'Equipe'},
        ),
        migrations.AlterField(
            model_name='member',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descrição completa'),
        ),
        migrations.AlterField(
            model_name='member',
            name='description_pt_br',
            field=models.TextField(verbose_name='Descrição completa'),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.membergroup', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='member',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='short_description_pt_br',
            field=models.CharField(max_length=255, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='member',
            name='short_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome da equipe'),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='name_pt_br',
            field=models.CharField(max_length=120, verbose_name='Nome da equipe'),
        ),
    ]
