# Generated by Django 3.2 on 2024-02-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_navigatecampaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigatecampaigns',
            name='related_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.campaign', verbose_name='Campanha Relacionada'),
        ),
    ]
