# Generated by Django 4.2 on 2024-03-18 17:48

from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('apps', '0014_navigatecampaigns_related_campaigns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigatecampaigns',
            name='related_campaigns',
            field=models.ManyToManyField(blank=True, help_text='Caso não queira o preenchimento automático das Campanhas, você deve selecionar nesse campo as Campanhas que deseja mostrar.', related_name='related_campaigns_navigate_campaigns_plugin', to='apps.campaign', verbose_name='Campanhas relacionadas'),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Evento da Timeline',
                'verbose_name_plural': 'Eventos da Timeline',
                'ordering': ['-year', '-month'],
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
