# Generated by Django 4.2 on 2024-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_navigatecampaigns_related_campaigns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['-year', '-month', '-day'], 'verbose_name': 'Evento da Timeline', 'verbose_name_plural': 'Eventos da Timeline'},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='day',
            field=models.IntegerField(default=1, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_context',
            field=models.CharField(choices=[('mundo', 'Mundo'), ('nossas', 'Nossas')], default='mundo', max_length=6),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Ano'),
        ),
    ]
