# Generated by Django 4.2 on 2024-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AddField(
            model_name='counter',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='end_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de fim'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='start_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de inicio'),
        ),
    ]
