# Generated by Django 3.2 on 2023-12-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeScss',
            fields=[
                ('theme_file', models.FileField(blank=True, null=True, upload_to='themes/', verbose_name='Arquivo do Tema')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
            ],
            options={
                'verbose_name': 'Theme Scss',
            },
        ),
    ]
