# Generated by Django 3.2 on 2023-12-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themescss',
            name='theme_file',
        ),
        migrations.AddField(
            model_name='themescss',
            name='theme',
            field=models.TextField(blank=True, null=True, verbose_name='Tema'),
        ),
    ]
