# Generated by Django 3.2 on 2023-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='membergroup',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='member',
            name='description_pt_br',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='member',
            name='short_description_pt_br',
            field=models.CharField(default='', max_length=255, verbose_name='short_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membergroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='membergroup',
            name='name_pt_br',
            field=models.CharField(default='', max_length=120, verbose_name='name'),
            preserve_default=False,
        ),
    ]
