# Generated by Django 3.2 on 2023-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='align',
        ),
        migrations.AddField(
            model_name='column',
            name='alignment_x',
            field=models.CharField(choices=[('items-center', 'Centro'), ('items-left', 'Esquerda'), ('items-right', 'Direita')], default='items-center', max_length=30, verbose_name='Alinhamento Horizontal'),
        ),
        migrations.AddField(
            model_name='column',
            name='alignment_y',
            field=models.CharField(choices=[('justify-start', 'Acima'), ('justify-center', 'Ao centro'), ('justify-end', 'Abaixo')], default='justify-start', max_length=30, verbose_name='Alinhamento Vertical'),
        ),
    ]
