# Generated by Django 3.2 on 2023-05-31 17:23

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='frontend_block', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='título')),
                ('slug', models.SlugField(blank=True, help_text='a parte do título que é usada na URL', max_length=80, verbose_name='slug')),
                ('menu_title', models.CharField(blank=True, help_text='padrão é igual ao título do bloco', max_length=50, verbose_name='título do menu')),
                ('menu_hidden', models.BooleanField(default=False, verbose_name='esconder menu?')),
                ('hidden', models.BooleanField(default=False, verbose_name='esconder bloco?')),
                ('spacing', models.CharField(default='py-7', max_length=30, verbose_name='margem')),
                ('background_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('rgb(0,0,0)', 'black'), ('rgb(226 232 240)', 'slate'), ('rgb(209 213 219)', 'gray'), ('rgb(212 212 216)', 'zinc'), ('rgb(220 38 38)', 'red')])),
                ('layout', models.CharField(blank=True, choices=[('hero', 'Hero'), ('hero_nobrand', 'Hero Sem logo'), ('tree_columns', '3 Colunas'), ('four_columns', '4 Colunas'), ('two_columns_a', '2 Colunas - 6x6'), ('two_columns_b', '2 Colunas - 4x8'), ('signature', 'Assinatura'), ('signature_partners_a', '2 Colunas - Assinatura com parceiros'), ('signature_partners_b', '1 Coluna - Assinatura com parceiros')], max_length=75, null=True, verbose_name='Layout')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem de fundo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
