# Generated by Django 3.2 on 2023-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20230531_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='align',
            field=models.CharField(choices=[('justify-items-center', 'Centro'), ('justify-items-left', 'Esquerda'), ('justify-items-right', 'Direita')], default='justify-items-center', max_length=30, verbose_name='Alinhamento'),
        ),
    ]
