# Generated by Django 3.2 on 2023-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20230601_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='layout',
        ),
        migrations.AlterField(
            model_name='block',
            name='spacing',
            field=models.CharField(choices=[('py-8', 'Extra small'), ('py-10', 'Small'), ('py-12', 'Default'), ('py-14', 'Large'), ('py-16', 'Extra large')], default='py-12', max_length=30, verbose_name='espaçamento'),
        ),
    ]
