# Generated by Django 3.2 on 2023-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20230602_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='cols',
            field=models.CharField(choices=[('grid-cols-1', '1 Coluna'), ('grid-cols-1 md:grid-cols-2', '2 Colunas'), ('grid-cols-1 md:grid-cols-3', '3 Colunas'), ('grid-cols-1 sm:grid-cols-2 md:grid-cols-4', '4 Colunas'), ('grid-cols-1 md:grid-cols-[1fr_2fr]', '2 colunas, 4 x 8')], default='grid-cols-1', max_length=80, verbose_name='Colunas'),
        ),
    ]
