# Generated by Django 3.2 on 2023-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20230602_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='alignment',
            field=models.CharField(blank=True, choices=[('justify-items-center', 'Centralizar')], max_length=30, null=True, verbose_name='alinhamento'),
        ),
        migrations.AlterField(
            model_name='button',
            name='rounded',
            field=models.CharField(blank=True, choices=[('rounded-none', 'Sem arredondamento'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-xl', 'Extra Large')], max_length=30, null=True, verbose_name='Arredondamento'),
        ),
    ]
