# Generated by Django 3.2 on 2023-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20230602_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='alignment',
            field=models.CharField(blank=True, choices=[('grid justify-items-center', 'Centralizar')], max_length=30, null=True, verbose_name='alinhamento'),
        ),
    ]
