# Generated by Django 3.2 on 2023-06-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('frontend', '0009_auto_20230602_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='frontend_socialmedia', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='block',
            name='alignment',
            field=models.CharField(blank=True, choices=[('grid justify-items-center', 'Centralizar')], max_length=30, null=True, verbose_name='alinhamento'),
        ),
        migrations.CreateModel(
            name='SocialMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('kind', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('site', 'Site')], max_length=100, verbose_name='Tipo')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Ícone')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.socialmedia')),
            ],
        ),
    ]
