# Generated by Django 3.2 on 2023-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20230602_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='alignment',
            field=models.CharField(blank=True, choices=[('grid justify-items-center', 'Centralizar'), ('grid justify-items-start', 'Esquerda'), ('grid justify-items-end', 'Direita')], default='grid justify-items-start', max_length=30, null=True, verbose_name='alinhamento'),
        ),
    ]
