# Generated by Django 3.2 on 2023-06-12 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('frontend', '0011_alter_block_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='frontend_partners', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='socialmediaitem',
            name='url',
            field=models.CharField(help_text='Insira a URL com https://', max_length=100, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='PartnersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Insira a URL com https://', max_length=100, null=True, verbose_name='URL')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.partners')),
            ],
        ),
    ]
