# Generated by Django 3.2 on 2023-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_block_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaitem',
            name='url',
            field=models.CharField(help_text='Insira a URL com https://', max_length=100, verbose_name='URL'),
        ),
    ]
