# Generated by Django 3.2 on 2023-06-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_block_alignment'),
        ('frontend', '0012_alter_socialmediaitem_url'),
        ('frontend', '0012_auto_20230612_1622'),
    ]

    operations = [
    ]
