# Generated by Django 3.2 on 2023-06-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('frontend', '0013_merge_20230613_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
