# Generated by Django 3.2 on 2023-06-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('frontend', '0014_auto_20230613_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='frontend_column', serialize=False, to='cms.cmsplugin')),
                ('align', models.CharField(choices=[('justify-items-center', 'Centro'), ('justify-items-left', 'Esquerda'), ('justify-items-right', 'Direita')], default='justify-items-center', max_length=30, verbose_name='Alinhamento')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='grid',
            name='align',
        ),
    ]
