# Generated by Django 3.2 on 2023-06-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('frontend', '0015_auto_20230613_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
