# Generated by Django 3.2 on 2023-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20230613_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersitem',
            name='external_icon',
            field=models.URLField(blank=True, help_text='If provided, overrides the embedded image. Certain options such as cropping are not applicable to external images.', max_length=255, null=True, verbose_name='External image'),
        ),
        migrations.AlterField(
            model_name='socialmediaitem',
            name='url',
            field=models.URLField(default='#', help_text='Insira a URL com https://', max_length=100, verbose_name='URL'),
        ),
    ]
