# Generated by Django 3.2 on 2023-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20230613_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaitem',
            name='external_icon',
            field=models.URLField(blank=True, help_text='If provided, overrides the embedded image. Certain options such as cropping are not applicable to external images.', max_length=255, null=True, verbose_name='External image'),
        ),
    ]
