# Generated by Django 3.2 on 2023-06-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_socialmediaitem_external_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaitem',
            old_name='external_icon',
            new_name='external_picture',
        ),
        migrations.RenameField(
            model_name='socialmediaitem',
            old_name='icon',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='partnersitem',
            name='external_icon',
        ),
        migrations.RemoveField(
            model_name='partnersitem',
            name='icon',
        ),
    ]
