# Generated by Django 3.2 on 2023-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20230613_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='cols',
            field=models.CharField(choices=[('grid-cols-2 md:grid-cols-4', '4 Colunas'), ('grid-cols-2 md:grid-cols-6', '6 Colunas')], default='grid-cols-2 md:grid-cols-4', max_length=50, verbose_name='Colunas'),
        ),
    ]
