# Generated by Django 3.2 on 2023-06-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('frontend', '0021_partners_cols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersitem',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='partnersitem',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='socialmediaitem',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='socialmediaitem',
            name='plugin',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='PartnersItem',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMediaItem',
        ),
    ]
