services:
  eleicaodoano:
    image: ${ELEICOES_DOCKER_IMAGE:-nossas/eleicoes-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_eleicoes.eleicaodoano.settings
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${ELEICAODOANO_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${ELEICAODOANO_RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${ELEICAODOANO_RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.eleicaodoano.priority=10
      - traefik.http.services.eleicaodoano.loadbalancer.server.port=8000
      - traefik.http.routers.eleicaodoano.tls=true
      - traefik.http.routers.eleicaodoano.tls.certresolver=myresolver
      - traefik.http.routers.eleicaodoano.rule=${ELEICAODOANO_TRAEFIK_ROUTERS_RULE:-HostRegexp(`eleicaodoano.staging.bonde.org`,`www.eleicaodoano.staging.bonde.org`)}

  votepeloclima:
    image: ${ELEICOES_DOCKER_IMAGE:-nossas/eleicoes-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_eleicoes.votepeloclima.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${VOTEPELOCLIMA_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:-"us-east-1"}
      - AWS_STORAGE_BUCKET_NAME=${VOTEPELOCLIMA_AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${VOTEPELOCLIMA_RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${VOTEPELOCLIMA_RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-etcd}
      - ETCD_PORT=${ETCD_PORT:-2379}
      - SMTP_HOST=${SMTP_HOST:-fake-smtp}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASS=${SMTP_PASS:-pass}
    labels:
      - traefik.enable=true
      - traefik.http.routers.votepeloclima.priority=10
      - traefik.http.services.votepeloclima.loadbalancer.server.port=8000
      - traefik.http.routers.votepeloclima.tls=true
      - traefik.http.routers.votepeloclima.tls.certresolver=myresolver
      - traefik.http.routers.votepeloclima.rule=${VOTEPELOCLIMA_TRAEFIK_ROUTERS_RULE:-HostRegexp(`votepeloclima.staging.bonde.org`,`www.votepeloclima.staging.bonde.org`)}
      # Regras de upload
      - traefik.http.middlewares.votepeloclima.buffering.maxRequestBodyBytes=62914560
      - traefik.http.middlewares.votepeloclima.buffering.maxResponseBodyBytes=62914560

  nossas:
    image: ${NOSSAS_DOCKER_IMAGE:-nossas/nossas-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_nossas.nossas.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${NOSSAS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nossas.priority=10
      - traefik.http.services.nossas.loadbalancer.server.port=8000
      - traefik.http.routers.nossas.tls=true
      - traefik.http.routers.nossas.tls.certresolver=myresolver
      - traefik.http.routers.nossas.rule=${NOSSAS_TRAEFIK_ROUTERS_RULE:-HostRegexp(`nossas.staging.bonde.org`,`www.nossas.staging.bonde.org`)}

  observatorio:
    image: ${ADP_DOCKER_IMAGE:-nossas/amazoniadepe-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_amazonia_de_pe.adp.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${ADP_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.observatorio.priority=10
      - traefik.http.services.observatorio.loadbalancer.server.port=8000
      - traefik.http.routers.observatorio.tls=true
      - traefik.http.routers.observatorio.tls.certresolver=myresolver
      - traefik.http.routers.observatorio.rule=${ADP_TRAEFIK_ROUTERS_RULE:-HostRegexp(`observatorio.staging.bonde.org`, `www.observatorio.staging.bonde.org`)}
  
  observatorio-mapa:
    image: ${ADP_MAPA_DOCKER_IMAGE:-nossas/fpnd-mapa:v1.0}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - MY_APP_URL_AJUDA=${ADP_MAPA_URL_AJUDA}
      - MY_APP_URL_COMO_AGIR=${ADP_MAPA_URL_COMO_AGIR}
      - MY_APP_URL_INFO_DATA=${ADP_MAPA_URL_INFO_DATA}
      - MY_APP_URL_MAP_DATA=${ADP_MAPA_URL_MAP_DATA}
      - MY_APP_URL_MVT=${ADP_MAPA_URL_MVT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.observatorio-mapa.priority=10
      - traefik.http.services.observatorio-mapa.loadbalancer.server.port=80
      - traefik.http.routers.observatorio-mapa.tls=true
      - traefik.http.routers.observatorio-mapa.tls.certresolver=myresolver
      - traefik.http.routers.observatorio-mapa.rule=${ADP_MAPA_TRAEFIK_ROUTERS_RULE:-HostRegexp(`observatorio-mapa.staging.bonde.org`)}

networks:
  default:
    name: bonde
