services:
    cms:
      image: ${DOCKER_IMAGE:-nossas/cms:main}
      restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
      pull_policy: always
      environment:
        - DEBUG=${DEBUG:-True}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
        - CMS_DATABASE_URL=${CMS_DATABASE_URL}
        - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.cms.priority=10
        - traefik.http.services.cms.loadbalancer.server.port=8000
        - traefik.http.routers.cms.tls=true
        - traefik.http.routers.cms.tls.certresolver=myresolver
        - traefik.http.routers.cms.rule=HostRegexp(`aeleicaodoano.org`,`{subdomain:[a-z]+}.aeleicaodoano.org`,`cms.bonde.org`,`{subdomain:[a-z]+}.cms.bonde.org`)
        # - traefik.http.routers.cms.tls.domains[0].main=aeleicaodoano.org
        # - traefik.http.routers.cms.tls.domains[0].sans=*.aeleicaodoano.org

networks:
  default:
    name: bonde