services:
  cms:
    image: ${DOCKER_IMAGE:-nossas/cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${CMS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.priority=10
      - traefik.http.services.cms.loadbalancer.server.port=8000
      - traefik.http.routers.cms.tls=true
      - traefik.http.routers.cms.tls.certresolver=myresolver
      - traefik.http.routers.cms.rule=${TRAEFIK_ROUTERS_RULE:-"HostRegexp(`cms.staging.bonde.org`)"}
  
  eleicaodoano:
    image: ${ELEICAO_DO_ANO_DOCKER_IMAGE:-nossas/cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=eleicoes.eleicao.settings.base
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${CMS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.priority=10
      - traefik.http.services.cms.loadbalancer.server.port=8000
      - traefik.http.routers.cms.tls=true
      - traefik.http.routers.cms.tls.certresolver=myresolver
      - traefik.http.routers.cms.rule=${TRAEFIK_ROUTERS_RULE:-"HostRegexp(`cms.staging.bonde.org`)"}
  

  nossas:
    image: ${NOSSAS_DOCKER_IMAGE:-nossas/nossas-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_nossas.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${NOSSAS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nossas.priority=10
      - traefik.http.services.nossas.loadbalancer.server.port=8000
      - traefik.http.routers.nossas.tls=true
      - traefik.http.routers.nossas.tls.certresolver=myresolver
      - traefik.http.routers.nossas.rule=${NOSSAS_TRAEFIK_ROUTERS_RULE:-"HostRegexp(`nossas.staging.bonde.org`)"}

  adp:
    image: ${ADP_DOCKER_IMAGE:-nossas/cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=adp.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${ADP_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
    labels:
      - traefik.enable=true
      - traefik.http.routers.adp.priority=10
      - traefik.http.services.adp.loadbalancer.server.port=8000
      - traefik.http.routers.adp.tls=true
      - traefik.http.routers.adp.tls.certresolver=myresolver
      - traefik.http.routers.adp.rule=${ADP_TRAEFIK_ROUTERS_RULE:-"HostRegexp(`adp.staging.bonde.org`)"}

  adp-mapa:
    image: ${ADP_MAPA_DOCKER_IMAGE:-nossas/fpnd-mapa:v1.0}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - MY_APP_URL_AJUDA=${ADP_MAPA_URL_AJUDA}
      - MY_APP_URL_COMO_AGIR=${ADP_MAPA_URL_COMO_AGIR}
      - MY_APP_URL_INFO_DATA=${ADP_MAPA_URL_INFO_DATA}
      - MY_APP_URL_MAP_DATA=${ADP_MAPA_URL_MAP_DATA}
      - MY_APP_URL_MVT=${ADP_MAPA_URL_MVT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.adp-mapa.priority=10
      - traefik.http.services.adp-mapa.loadbalancer.server.port=80
      - traefik.http.routers.adp-mapa.tls=true
      - traefik.http.routers.adp-mapa.tls.certresolver=myresolver
      - traefik.http.routers.adp-mapa.rule=${ADP_MAPA_TRAEFIK_ROUTERS_RULE:-"HostRegexp(`adp-mapa.staging.bonde.org`)"}

networks:
  default:
    name: bonde
