services:
    cms:
      image: ${DOCKER_IMAGE:-nossas/cms:main}
      restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
      pull_policy: always
      environment:
        - DEBUG=${DEBUG:-True}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
        - CMS_DATABASE_URL=${CMS_DATABASE_URL}
        - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
        - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
        - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
        - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      labels:
        - traefik.enable=true
        - traefik.http.routers.cms.priority=10
        - traefik.http.services.cms.loadbalancer.server.port=8000
        - traefik.http.routers.cms.tls=true
        - traefik.http.routers.cms.tls.certresolver=myresolver
        - traefik.http.routers.cms.rule=${TRAEFIK_ROUTERS_RULE:-"HostRegexp(`cms.staging.bonde.org`)"}

    # prometheus:
    #   image: prom/prometheus
    #   restart: 'no'
    #   user: root
    #   volumes:
    #     - prometheus_data:/prometheus
    #     # - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #   labels:
    #     - traefik.enable=true
    #     - traefik.http.services.prometheus.loadbalancer.server.port=9090
    #     - traefik.http.routers.prometheus.tls=true
    #     - traefik.http.routers.prometheus.tls.certresolver=myresolver
    
    # grafana:
    #   image: grafana/grafana
    #   user: root
    #   environment:
    #     GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    #   restart: 'no'
    #   volumes:
    #     - grafana_data:/var/lib/grafana
    #   depends_on:
    #     - prometheus
    #   labels:
    #     - traefik.enable=true
    #     - traefik.http.services.grafana.loadbalancer.server.port=3000
    #     - traefik.http.routers.grafana.tls=true
    #     - traefik.http.routers.grafana.tls.certresolver=myresolver

networks:
  default:
    name: bonde

# volumes:
#   prometheus_data:
#     driver: local
#   grafana_data:
#     driver: local
