services:
  eleicaodoano:
    image: ${ELEICOES_DOCKER_IMAGE:-nossas/eleicoes-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_eleicoes.eleicaodoano.settings.production
      - DEBUG=${ELEICAODOANO_DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${ELEICAODOANO_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=eleicaodoano
      - RECAPTCHA_PUBLIC_KEY=${ELEICAODOANO_RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${ELEICAODOANO_RECAPTCHA_PRIVATE_KEY}
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
      - ADMINS=${ADMINS:-"('Admin', 'admin@localhost'),"}
      - SMTP_HOST=${SMTP_HOST:-fake-smtp}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASS=${SMTP_PASS:-pass}
    labels:
      - traefik.enable=true
      - traefik.http.routers.eleicaodoano.priority=999
      - traefik.http.services.eleicaodoano.loadbalancer.server.port=8000
      - traefik.http.routers.eleicaodoano.tls=true
      - traefik.http.routers.eleicaodoano.tls.certresolver=myresolver
      - traefik.http.routers.eleicaodoano.rule=${ELEICAODOANO_TRAEFIK_ROUTERS_RULE:-HostRegexp(`eleicaodoano.staging.bonde.org`,`www.eleicaodoano.staging.bonde.org`)}

  nossas:
    image: ${NOSSAS_DOCKER_IMAGE:-nossas/nossas-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    environment:
      - DJANGO_SETTINGS_MODULE=org_nossas.nossas.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"docker.localhost"}
      - CMS_DATABASE_URL=${NOSSAS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=openactiontool-cms
      - DISABLE_RECAPTCHA=${DISABLE_RECAPTCHA}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - ETCD_HOST=${ETCD_HOST:-"etcd"}
      - ETCD_PORT=${ETCD_PORT:-2379}
      - ADMINS=${ADMINS:-"('Admin', 'admin@localhost'),"}
      - SMTP_HOST=${SMTP_HOST:-fake-smtp}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASS=${SMTP_PASS:-pass}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nossas.priority=999
      - traefik.http.services.nossas.loadbalancer.server.port=8000
      - traefik.http.routers.nossas.tls=true
      - traefik.http.routers.nossas.tls.certresolver=myresolver
      - traefik.http.routers.nossas.rule=${NOSSAS_TRAEFIK_ROUTERS_RULE:-HostRegexp(`nossas.staging.bonde.org`,`www.nossas.staging.bonde.org`)}
  
  votepeloclima:
    image: ${VPC_DOCKER_IMAGE:-nossas/eleicoes-cms:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      - DJANGO_SETTINGS_MODULE=org_eleicoes.votepeloclima.settings.production
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-"votepeloclima.localhost"}
      - SECRET_KEY=${VPC_SECRET_KEY}
      - CMS_DATABASE_URL=${VPC_CMS_DATABASE_URL}
      - BONDE_DATABASE_URL=${BONDE_DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:-"us-east-1"}
      - AWS_STORAGE_BUCKET_NAME=votepeloclima
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - BONDE_ACTION_API_URL=${BONDE_ACTION_API_URL}
      - BONDE_ACTION_SECRET_KEY=${BONDE_ACTION_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST:-fake-smtp}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASS=${SMTP_PASS:-pass}
      - REDIRECT_MIDDLEWARE_ROOT_DOMAIN=${REDIRECT_MIDDLEWARE_ROOT_DOMAIN:-"votepeloclima.localhost"}
      - REDIRECT_MIDDLEWARE_LIST_DOMAIN=${REDIRECT_MIDDLEWARE_LIST_DOMAIN:-"votepeloclima.localhost.devel"}
      - ADMINS=${ADMINS:-"('Admin', 'admin@localhost'),"}
    labels:
      - traefik.enable=true
      - traefik.http.routers.votepeloclima.priority=10
      - traefik.http.services.votepeloclima.loadbalancer.server.port=8000
      - traefik.http.routers.votepeloclima.tls=true
      - traefik.http.routers.votepeloclima.tls.certresolver=myresolver
      - custom.servicename=votepeloclima
      - traefik.http.routers.votepeloclima.rule=${VPC_TRAEFIK_ROUTERS_RULE:-HostRegexp(`votepeloclima.staging.bonde.org`,`www.votepeloclima.staging.bonde.org`)}

networks:
  default:
    name: bonde
