global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: django
    metrics_path: '/monitoring/metrics'
    static_configs:
      - targets: ['cms.staging.bonde.org']
