# Generated by Django 4.2 on 2024-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0002_accordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'default'), ('flush', 'flush')], default='', max_length=7),
        ),
    ]
