# Generated by Django 4.2 on 2024-05-14 14:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0003_alter_accordion_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='accordion',
            name='grid_columns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accordion',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
