# Generated by Django 4.2 on 2024-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0004_accordion_bg_color_accordion_grid_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='context',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=30, null=True),
        ),
    ]
