# Generated by Django 4.2 on 2024-05-17 17:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0005_accordion_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Sobrescreve o valor definido na Cor de Contexto', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor do Fundo'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='context',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], help_text='Define um padrão de Cor de Fundo e Cor de Texto', max_length=30, null=True, verbose_name='Cor de Contexto'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='grid_columns',
            field=models.PositiveSmallIntegerField(default=0, help_text='Use 0 para renderizar um item abaixo do outro sem espaçamento entre eles', verbose_name='Nº de Colunas'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'default'), ('flush', 'flush')], default='', max_length=7, verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Sobrescreve o valor definido na Cor de Contexto', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor do Texto'),
        ),
    ]
