# Generated by Django 3.2 on 2023-05-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('campaign', '0002_auto_20230518_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='campaign_actionbutton', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=80, verbose_name='título')),
                ('action_url', models.CharField(help_text='slug do bloco usado na URL', max_length=80, verbose_name='endereço da ação')),
                ('bg_color', models.CharField(blank=True, default='blue', max_length=50, verbose_name='cor do fundo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
