# Generated by Django 3.2 on 2023-06-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('campaign', '0007_delete_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='campaign_pressure', serialize=False, to='cms.cmsplugin')),
                ('widget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='column',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='row',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='ActionButton',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
