# Generated by Django 3.2 on 2023-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_alter_pressure_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de resposta'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='sender_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='sharing',
            field=models.JSONField(blank=True, null=True, verbose_name='Opções de compartilhamento'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='thank_email_body',
            field=models.TextField(blank=True, null=True, verbose_name='Corpo do e-mail de agradecimento'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='thank_email_subject',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Assunto do e-mail de agradecimento para quem vai pressionar'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='whatsapp_text',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem para o whatsapp'),
        ),
    ]
