# Generated by Django 3.2 on 2023-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_rename_faviconextension_iconextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetgroup',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='targetgroup',
            name='targets',
        ),
        migrations.AddField(
            model_name='pressure',
            name='targets',
            field=models.JSONField(default='', verbose_name='Alvos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='TargetGroup',
        ),
    ]
