# Generated by Django 3.2 on 2023-06-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20230626_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressure',
            old_name='widget',
            new_name='widget_id',
        ),
    ]
