# Generated by Django 3.2 on 2023-06-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ga',
            options={'verbose_name': 'Google Analytics'},
        ),
    ]
