# Generated by Django 3.2 on 2023-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0002_alter_ga_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ga',
            name='uuid',
            field=models.CharField(blank=True, help_text='Ex. G-XXXXXXXXXX', max_length=15, null=True, verbose_name='ID da métrica'),
        ),
    ]
