# Generated by Django 4.2 on 2024-07-05 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=150)),
                ('ballot_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf_cnpj', models.CharField(max_length=30)),
                ('tse_id', models.CharField(blank=True, max_length=30, null=True)),
                ('number_id', models.PositiveIntegerField()),
                ('intended_position', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=60)),
                ('is_collective_mandate', models.BooleanField(blank=True, default=False)),
                ('political_party', models.CharField(max_length=60)),
                ('video', models.FileField(blank=True, null=True, upload_to='cadidatures/videos/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='cadidatures/photos/')),
                ('gender', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('sexuality', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('employment', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.TextField()),
                ('flags', models.JSONField(blank=True)),
                ('appointments', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('validations', models.JSONField(blank=True)),
                ('candidature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidature.candidature')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
