# Generated by Django 4.2 on 2024-07-08 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidature', '0002_candidatureflow_delete_candidaturestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatureflow',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatureflow',
            name='validations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
