# Generated by Django 4.2 on 2024-07-08 15:41

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0003_alter_candidatureflow_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatureflow',
            name='properties',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
