# action.yml
name: 'Pelican to Github Pages'
description: 'Generate the Pelican output and deploy to Github Pages'

branding:
  icon: 'home'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile/Dockerfile'  

inputs:
  GH_PAGES_BRANCH:
    description: 'override the default `gh-pages` deployment branch'
    required: false
    default: 'gh-pages'
  GH_PAGES_CNAME:
    description: 'specify the custom domain configured for the output branch'
    required: false
    default: none
  PELICAN_CONFIG_FILE:
    description: 'override the default `pelicanconf.py` config file'
    required: false
    default: publishconf.py
  PELICAN_CONTENT_FOLDER:
    description: 'override the default `content` content folder'
    required: false
    default: content
  PELICAN_THEME_FOLDER:
    description: 'setup the theme folder with package.json file, is required if you need install node modules'
    required: false
  PELICAN_REQUIREMENTS_FILE:
    description: 'setup location requiements.txt file'
    required: false
