# Generated by Django 3.2 on 2023-03-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='form_entries_formdefinition', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=255, verbose_name='Form Name')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('form_template', models.CharField(blank=True, choices=[('form_entries/templates/default.html', 'Default')], default='form_entries/templates/default.html', max_length=150, verbose_name='Form Template')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('email', 'Email'), ('number', 'Number'), ('phone', 'Phone'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkbox_multiple', 'Multi Checkbox'), ('select', 'Drop down'), ('radio', 'Radio'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('password', 'Password'), ('hidden', 'Hidden')], default='text', max_length=100, verbose_name='Field Type')),
                ('label', models.CharField(max_length=255, verbose_name='name')),
                ('field_name', models.CharField(blank=True, max_length=255, verbose_name='Custom Field Name')),
                ('placeholder_text', models.CharField(blank=True, max_length=100, verbose_name='Placeholder Text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('help_text', models.TextField(blank=True, help_text='A description / instructions for this field.', verbose_name='Description')),
                ('initial', models.CharField(blank=True, max_length=255, verbose_name='Default Value')),
                ('choice_values', models.TextField(blank=True, help_text='Enter options one per line. For "File Upload" field type, enter allowed filetype (e.g .pdf) one per line.', verbose_name='Choices')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Position')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_entries.formdefinition')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'ordering': ('position',),
            },
        ),
    ]
