# Generated by Django 4.2 on 2024-05-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('start_number', models.IntegerField(verbose_name='Número de inicio')),
                ('end_number', models.IntegerField(verbose_name='Número de fim')),
                ('measurement', models.CharField(blank=True, max_length=140, null=True, verbose_name='Unidade de medida')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tooltip_text', models.TextField(blank=True, null=True, verbose_name='Texto do Tooltip')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
