# Generated by Django 4.2 on 2024-05-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_end_date_counter_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='start_date',
            new_name='initial_date',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='start_number',
            new_name='initial_number',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='end_date',
            new_name='target_date',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='end_number',
            new_name='target_number',
        ),
    ]
