# Generated by Django 4.2 on 2024-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_rename_start_date_counter_initial_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='tooltip_text',
        ),
    ]
