# Generated by Django 4.2 on 2024-05-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('file_scss', models.FileField(blank=True, null=True, upload_to='themes/')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
            ],
            options={
                'verbose_name': 'Google Analytics',
            },
        ),
    ]
