# Generated by Django 4.2 on 2024-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Design System'},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='file_scss',
        ),
        migrations.AddField(
            model_name='theme',
            name='scss',
            field=models.TextField(blank=True, null=True),
        ),
    ]
