# Generated by Django 4.2 on 2024-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_alter_theme_options_remove_theme_file_scss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='scss',
        ),
        migrations.AddField(
            model_name='theme',
            name='scss_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
