# Generated by Django 4.2 on 2024-05-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ds', '0005_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='brand',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='navbar',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
