# Generated by Django 4.2 on 2024-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0007_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='alignment',
            field=models.CharField(blank=True, choices=[('', 'start'), ('center', 'center'), ('flex-end', 'end')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='context',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=30, null=True),
        ),
    ]
