# Generated by Django 4.2 on 2024-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0008_navbar_alignment_alter_navbar_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='placement',
            field=models.CharField(blank=True, choices=[('', 'default'), ('fixed-top', 'fixed'), ('sticky-top', 'sticky')], max_length=30, null=True),
        ),
    ]
