# Generated by Django 4.2 on 2024-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0009_navbar_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active_styled',
            field=models.CharField(blank=True, choices=[('', 'default'), ('underline', 'underline')], max_length=30, null=True),
        ),
    ]
