# Generated by Django 4.2 on 2024-06-03 14:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ds', '0010_menu_active_styled'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='favicon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Favicon'),
        ),
    ]
