# Generated by Django 4.2 on 2024-06-05 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ds', '0011_theme_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('title', models.CharField(blank=True, help_text='Limite de 60 caracteres', max_length=60, null=True, verbose_name='Título')),
                ('description', models.CharField(blank=True, help_text='Limite de 155 caracteres', max_length=155, null=True, verbose_name='Descrição')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem de compartilhamento')),
            ],
            options={
                'verbose_name': 'Metadados SEO',
            },
        ),
    ]
