# Generated by Django 4.2 on 2024-06-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('ds', '0011_theme_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuExtraLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Link interno')),
                ('menu_plugin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_link', to='ds.menu')),
            ],
        ),
    ]
