# Generated by Django 4.2 on 2024-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0011_theme_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
