# Generated by Django 4.2 on 2024-06-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0012_menu_attributes'),
        ('ds', '0012_seo'),
    ]

    operations = [
    ]
