# Generated by Django 4.2 on 2024-06-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0012_menuextralink'),
        ('ds', '0013_merge_0012_menu_attributes_0012_seo'),
    ]

    operations = [
    ]
