# Generated by Django 4.2.1 on 2023-05-12 01:27

from django.db import migrations, models
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_actionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default='', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionpage',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='actionpage',
            name='theme',
            field=models.CharField(choices=[('css/default.css', 'Default'), ('css/custom.css', 'Custom')], max_length=20, verbose_name='Escolha seu tema'),
        ),
    ]
