# Generated by Django 4.2 on 2024-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0022_auto_20180620_1551'),
        ('publications', '0003_alter_publication_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('slug', 'parent', 'site')},
        ),
    ]
