# Generated by Django 3.2 on 2024-01-15 14:55

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullpageslider',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
