# Generated by Django 3.2 on 2024-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_auto_20240111_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='col',
            field=models.CharField(choices=[(' ', 'Auto'), ('g-col-1', 'Col 1'), ('g-col-2', 'Col 2'), ('g-col-3', 'Col 3'), ('g-col-4', 'Col 4'), ('g-col-5', 'Col 5'), ('g-col-6', 'Col 6'), ('g-col-7', 'Col 7'), ('g-col-8', 'Col 8'), ('g-col-9', 'Col 9'), ('g-col-10', 'Col 10'), ('g-col-11', 'Col 11'), ('g-col-12', 'Col 12')], default=' ', help_text='Defina manualmente o número de colunas que esta coluna ocupará.', max_length=15, verbose_name='Coluna'),
        ),
        migrations.AlterField(
            model_name='column',
            name='col_start_at',
            field=models.CharField(choices=[(' ', 'Auto'), ('g-start-1', 'Start at Col 1'), ('g-start-2', 'Start at Col 2'), ('g-start-3', 'Start at Col 3'), ('g-start-4', 'Start at Col 4'), ('g-start-5', 'Start at Col 5'), ('g-start-6', 'Start at Col 6'), ('g-start-7', 'Start at Col 7'), ('g-start-8', 'Start at Col 8'), ('g-start-9', 'Start at Col 9'), ('g-start-10', 'Start at Col 10'), ('g-start-11', 'Start at Col 11'), ('g-start-12', 'Start at Col 12')], default=' ', help_text='Defina em qual coluna o elemento deve iniciar.', max_length=30, verbose_name='Alinhamento horizontal da coluna'),
        ),
        migrations.AlterField(
            model_name='column',
            name='rows',
            field=models.CharField(choices=[(' ', 'Auto'), ('grid-row: 2', 'Linha 2'), ('grid-row: 3', 'Linha 3'), ('grid-row: 4', 'Linha 4')], default=' ', help_text='Escolha manualmente o número da linha que esta coluna ocupará.', max_length=15, verbose_name='Linhas'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='grid_layout',
            field=models.CharField(choices=[(' ', 'Auto'), ('g-col-12', '1 Coluna'), ('g-col-12 g-col-md-6', '2 Colunas'), ('g-col-12 g-col-md-4', '3 Colunas'), ('g-col-12 g-col-sm-2 g-col-4', '4 Colunas'), ('g-col-12 g-col-sm-2 g-col-2', '6 Colunas'), ('g-col-12 g-col-sm-2 g-col-1', '12 Colunas')], default=' ', help_text="Escolha 'Auto' para um layout responsivo automático ou para selecionar o número de colunas manualmente.", max_length=80, verbose_name='Layout do Grid'),
        ),
    ]
