# Generated by Django 3.2 on 2024-01-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_fullpageslider_background_image'),
        ('plugins', '0005_auto_20240115_1507'),
    ]

    operations = [
    ]
