# Generated by Django 3.2 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_auto_20240117_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='alignment_y',
            field=models.CharField(choices=[('justify-content: flex-start;', 'Acima'), ('justify-content: center;', 'Ao centro'), ('justify-content: flex-end;', 'Abaixo')], default='justify-content: flex-start;', max_length=50, verbose_name='Alinhamento vertical'),
        ),
    ]
