# Generated by Django 3.2 on 2024-01-24 14:10

from django.db import migrations, models
import django.db.models.deletion
import nossas.design.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0012_alter_column_alignment_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_header', serialize=False, to='cms.cmsplugin')),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(nossas.design.models.UIBackgroundMixin, 'cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='title',
            field=models.TextField(verbose_name='Título do Acordeon'),
        ),
    ]
