# Generated by Django 3.2 on 2024-01-26 18:57

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('plugins', '0013_auto_20240124_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem'),
        ),
    ]
