# Generated by Django 3.2 on 2024-01-30 19:04

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0017_image__transparent'),
        ('plugins', '0016_merge_0014_header_picture_0015_auto_20240129_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_card', serialize=False, to='cms.cmsplugin')),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('image', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
