# Generated by Django 3.2 on 2024-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='graphic_element',
            field=models.CharField(blank=True, choices=[('questionador', 'Questionador'), ('hub', 'Hub, Eixo'), ('impacto', 'Impacto'), ('empatico', 'Empático')], max_length=120, null=True),
        ),
    ]
