# Generated by Django 3.2 on 2024-02-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0021_auto_20240131_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_breadcrumb', serialize=False, to='cms.cmsplugin')),
                ('graphic_icon', models.CharField(blank=True, choices=[('hub', 'Hub, Eixo')], max_length=50, null=True, verbose_name='Ícone gráfico')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
