# Generated by Django 3.2 on 2024-02-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0024_container_fluid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_donationpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='Apoie este trabalho!', max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('button_text', models.CharField(blank=True, default='Próxima etapa', max_length=100, null=True, verbose_name='Texto do botão')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NewsletterPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_newsletterpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='Inscreva-se na Newsletter!', max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('button_text', models.CharField(blank=True, default='Inscrever-se', max_length=100, null=True, verbose_name='Texto do botão')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
