# Generated by Django 3.2 on 2024-02-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0024_container_fluid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumb',
            name='graphic_icon',
            field=models.CharField(blank=True, choices=[('questionador', 'Questionador'), ('hub', 'Hub, Eixo')], max_length=50, null=True, verbose_name='Ícone gráfico'),
        ),
    ]
