# Generated by Django 3.2 on 2024-02-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0025_donationpluginmodel_newsletterpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpluginmodel',
            name='button_text',
            field=models.CharField(blank=True, default='Enviar', max_length=100, null=True, verbose_name='Texto do botão'),
        ),
        migrations.AlterField(
            model_name='newsletterpluginmodel',
            name='title',
            field=models.CharField(blank=True, default='Fique por dentro!', max_length=255, null=True, verbose_name='Título'),
        ),
    ]
