# Generated by Django 3.2 on 2024-02-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0026_auto_20240205_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationPluginModel',
        ),
    ]
