# Generated by Django 3.2 on 2024-02-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0027_delete_donationpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpluginmodel',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
