# Generated by Django 3.2 on 2024-02-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0028_newsletterpluginmodel_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_accordionitem', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(verbose_name='Título do Acordeon')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='breadcrumb',
            name='graphic_icon',
            field=models.CharField(blank=True, choices=[('questionador', 'Questionador'), ('hub', 'Hub, Eixo')], max_length=50, null=True, verbose_name='Ícone gráfico'),
        ),
        migrations.DeleteModel(
            name='Accordion',
        ),
    ]
