# Generated by Django 3.2 on 2024-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0028_auto_20240220_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsharepluginmodel',
            name='attributes',
        ),
        migrations.AddField(
            model_name='socialsharepluginmodel',
            name='title',
            field=models.TextField(default='Título', verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='socialsharepluginmodel',
            name='selected_social_media',
            field=models.CharField(blank=True, max_length=255, verbose_name='Selecione as redes sociais'),
        ),
    ]
