# Generated by Django 4.2 on 2024-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0034_fullpageslider_background_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='grid_layout_mobile',
            field=models.CharField(choices=[(' ', 'Auto'), ('g-col-12', '1 Coluna'), ('g-col-12 g-col-md-6', '2 Colunas'), ('g-col-12 g-col-md-4', '3 Colunas'), ('g-col-12 g-col-md-3', '4 Colunas'), ('g-col-12 g-col-md-2', '6 Colunas'), ('g-col-12 g-col-md-1', '12 Colunas')], default='g-col-12', max_length=80, verbose_name='Layout do Grid Mobile'),
        ),
        migrations.AlterField(
            model_name='fullpageslider',
            name='background_size',
            field=models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover'), ('initial', 'Initial')], default='contain', max_length=8),
        ),
    ]
