# Generated by Django 3.2 on 2023-12-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('campaigns', '0002_auto_20231231_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='campaigns_campaignlistpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='QueryCampaignList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='campaigns.campaignlistpluginmodel')),
            ],
        ),
    ]
