# Generated by Django 3.2 on 2023-12-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignlistpluginmodel_querycampaignlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycampaignlist',
            name='attribute_name',
            field=models.CharField(choices=[('status', 'Status'), ('or', 'OU'), ('not', 'Não')], default='status', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querycampaignlist',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
