# Generated by Django 3.2 on 2024-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20231231_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('opened', 'Aberta'), ('closed', 'Fechada'), ('done', 'Concluída')], max_length=6),
        ),
        migrations.AlterField(
            model_name='querycampaignlist',
            name='attribute_name',
            field=models.CharField(choices=[('status', 'Status')], max_length=20),
        ),
    ]
