# Generated by Django 3.2 on 2024-01-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('campaigns', '0005_auto_20240103_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='header_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_header_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Cabeçalho Imagem'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='hide',
            field=models.BooleanField(blank=True, null=True, verbose_name='Esconder Campanha'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link da Campanha'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Nome da campanha'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_pt_br',
            field=models.TextField(verbose_name='Nome da campanha'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Nome da campanha'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem'),
        ),
    ]
