# Generated by Django 3.2 on 2024-01-15 15:38

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('campaigns', '0006_auto_20240115_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photos_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='campaign_photos_placeholder', to='cms.placeholder'),
        ),
    ]
