# Generated by Django 3.2 on 2024-01-15 15:46

from django.db import migrations
import tag_fields.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tag_fields', '0001_initial'),
        ('campaigns', '0007_campaign_photos_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=tag_fields.managers.ModelTagsManager(help_text='A comma-separated list of tags.', through='tag_fields.ModelTagIntFk', to='tag_fields.ModelTag', verbose_name='Tags'),
        ),
    ]
