# Generated by Django 3.2 on 2024-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20240115_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Esconder'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('opened', 'Aberta'), ('closed', 'Fechada'), ('done', 'Concluída')], max_length=6, verbose_name='Status'),
        ),
    ]
