# Generated by Django 3.2 on 2024-01-17 15:35

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('campaigns', '0010_auto_20240116_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mobilization_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Mobilização BONDE'),
        ),
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nome da grupo')),
                ('community_id', models.IntegerField(verbose_name='ID da Comunidade BONDE')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigngroup'),
        ),
    ]
