# Generated by Django 3.2 on 2024-01-17 19:34

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('campaigns', '0012_alter_campaigngroup_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campanha'},
        ),
        migrations.AlterModelOptions(
            name='campaigngroup',
            options={'verbose_name': 'Comunidade'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photos_placeholder',
        ),
        migrations.AddField(
            model_name='campaign',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='campaign_placeholder', to='cms.placeholder'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigngroup', verbose_name='Comunidade'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description_pt_br',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
