# Generated by Django 3.2 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20240117_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('opened', 'Aberta'), ('done', 'Concluída')], max_length=6, verbose_name='Status'),
        ),
    ]
