# Generated by Django 4.2 on 2024-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='label',
            field=models.CharField(default='Botão', max_length=100),
            preserve_default=False,
        ),
    ]
