# Generated by Django 4.2 on 2024-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_button_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='link_target',
            field=models.CharField(blank=True, choices=[('_blank', ' Blank'), ('_self', ' Self'), ('_parent', ' Parent'), ('_top', ' Top')], max_length=7, null=True),
        ),
    ]
