# Generated by Django 4.2 on 2024-04-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('link', '0003_button_link_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='external_link',
            field=models.CharField(blank=True, max_length=2040, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='internal_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
    ]
