# Generated by Django 4.2 on 2024-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_button_external_link_button_internal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='styled',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('outline', 'Outline'), ('invertedInverted', 'Inverted')], max_length=30, null=True),
        ),
    ]
