# Generated by Django 4.2 on 2024-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_button_styled'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='size',
            field=models.CharField(blank=True, choices=[('sm', 'Small'), ('', 'Medium'), ('lg', 'Large')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='styled',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('outline', 'Outline'), ('inverted', 'Inverted')], max_length=30, null=True),
        ),
    ]
