# Generated by Django 4.2 on 2024-05-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_button_size_alter_button_styled'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='icon_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10, blank=True),
        ),
    ]
