# Generated by Django 4.2 on 2024-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_alter_button_context_alter_button_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='link_target',
            field=models.CharField(choices=[('_self', 'Abrir na mesma aba'), ('_blank', 'Abrir em nova aba'), ('submit', 'Enviar formulário')], default='_self', help_text='Escolha como o link será aberto ao ser clicado', max_length=7, verbose_name='Comportamento do link'),
        ),
    ]
