# Generated by Django 4.2 on 2024-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_alter_button_link_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='icon_position',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita'), ('only', 'Somente Ícone')], default='left', max_length=10, verbose_name='Posição do ícone'),
        ),
        migrations.AlterField(
            model_name='button',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
