# Generated by Django 4.2 on 2024-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_alter_button_icon_position_alter_button_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
