# Generated by Django 3.2 on 2023-12-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route53', '0005_alter_vps_options'),
        ('traefik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('webpage@docker', 'Public'), ('cms@docker', 'CMS')], max_length=25)),
                ('dns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route53.hostedzone')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route53.vps')),
                ('subdomain', models.ForeignKey(blank=True, limit_choices_to={'record_type': 'A'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route53.recordset')),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
