# Generated by Django 3.2 on 2024-01-03 14:25

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('workload', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('responsibilities', djangocms_text_ckeditor.fields.HTMLField()),
                ('prerequisites', djangocms_text_ckeditor.fields.HTMLField()),
                ('benefits', djangocms_text_ckeditor.fields.HTMLField()),
                ('salary_estimate', models.CharField(max_length=80)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
