# Generated by Django 3.2 on 2024-01-03 14:31

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Descrição da vaga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Benefícios'),
        ),
        migrations.AlterField(
            model_name='job',
            name='condition',
            field=models.CharField(max_length=50, verbose_name='Condições de trabalho'),
        ),
        migrations.AlterField(
            model_name='job',
            name='prerequisites',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Pré-requisitos da vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Responsabilidades da vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_estimate',
            field=models.CharField(max_length=80, verbose_name='Estimativa salarial'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título da vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='workload',
            field=models.CharField(max_length=50, verbose_name='Carga horária'),
        ),
    ]
