# Generated by Django 3.2 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20240103_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('opened', 'Aberto'), ('closed', 'Fechado')], default='opened', max_length=20, verbose_name='Status da vaga'),
        ),
    ]
