# Generated by Django 4.2.6 on 2023-11-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route53', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('static_ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
