# Generated by Django 4.2.6 on 2023-11-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route53', '0002_vps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record_type', models.CharField(choices=[('SOA', 'Soa'), ('A', 'A'), ('TXT', 'Txt'), ('NS', 'Ns'), ('CNAME', 'Cname'), ('MX', 'Mx'), ('NAPTR', 'Naptr'), ('PTR', 'Ptr'), ('SRV', 'Srv'), ('SPF', 'Spf'), ('AAAA', 'Aaaa'), ('CAA', 'Caa'), ('DS', 'Ds')], max_length=5)),
                ('resource', models.JSONField(blank=True, null=True)),
                ('hosted_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route53.hostedzone')),
            ],
        ),
    ]
