# Generated by Django 4.2.6 on 2023-11-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route53', '0004_hostedzone_healtcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vps',
            options={'verbose_name': 'Instância', 'verbose_name_plural': 'Instâncias'},
        ),
    ]
