# Generated by Django 3.2 on 2023-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='spacing',
            field=models.CharField(choices=[('py-12', 'Pequeno'), ('py-20', 'Padrão'), ('py-28', 'Grande'), ('py-32', 'Muito grande')], default='py-20', max_length=30, verbose_name='espaçamento'),
        ),
    ]
