# Generated by Django 3.2 on 2023-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0003_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Ocultar bloco'),
        ),
        migrations.AlterField(
            model_name='block',
            name='menu_hidden',
            field=models.BooleanField(default=False, verbose_name='Ocultar menu'),
        ),
    ]
