# Generated by Django 3.2 on 2023-08-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0006_auto_20230821_2039'),
        ('landpage', '0006_auto_20230822_1436'),
    ]

    operations = [
    ]
