# Generated by Django 3.2 on 2024-01-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignListPluginModel',
        ),
    ]
