# Generated by Django 3.2 on 2024-01-26 17:10

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('apps', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('zipcode', models.CharField(max_length=10, verbose_name='CEP')),
                ('contact_mail', models.EmailField(max_length=254, verbose_name='E-mail de contato')),
                ('contact_phone', models.CharField(max_length=16, verbose_name='Telefone de contato')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Informações Institucionais',
            },
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
