# Generated by Django 3.2 on 2024-02-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('apps', '0006_auto_20240130_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigateCampaigns',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='apps_navigatecampaigns', serialize=False, to='cms.cmsplugin')),
                ('filter_tags', models.BooleanField(default=True, verbose_name='Filtrar por tags?')),
                ('filter_campaign_group', models.BooleanField(default=False, verbose_name='Filtrar por comunidade?')),
                ('related_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.campaign', verbose_name='Campanha Relacionada')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
