# Generated by Django 4.2 on 2024-03-07 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('apps', '0010_alter_member_options_alter_membergroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membergroup',
            options={'ordering': ('my_order', 'id'), 'verbose_name': 'Equipe'},
        ),
        migrations.AlterField(
            model_name='member',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição'),
        ),
        migrations.CreateModel(
            name='OurCitiesProject',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('url', models.URLField(blank=True, null=True)),
                ('picture', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagem')),
                ('related_campaigns', models.ManyToManyField(blank=True, to='apps.campaign', verbose_name='Campanhas relacionadas')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
