# Generated by Django 4.2 on 2024-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_membergroup_options_alter_member_my_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcitiesproject',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourcitiesproject',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Projeto'),
        ),
    ]
