# Generated by Django 4.2 on 2024-03-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_ourcitiesproject_name_alter_ourcitiesproject_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcitiesproject',
            name='hide_border',
            field=models.BooleanField(default=False, verbose_name='Remover borda'),
        ),
    ]
