# Generated by Django 4.2 on 2024-03-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_ourcitiesproject_hide_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigatecampaigns',
            name='related_campaigns',
            field=models.ManyToManyField(blank=True, related_name='related_campaigns_navigate_campaigns_plugin', to='apps.campaign', verbose_name='Campanhas relacionadas'),
        ),
        migrations.AlterField(
            model_name='navigatecampaigns',
            name='related_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_campaign_navigate_campaigns_plugin', to='apps.campaign', verbose_name='Campanha Relacionada'),
        ),
    ]
