# Generated by Django 4.2 on 2024-06-11 14:00

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('apps', '0016_alter_timelineevent_options_timelineevent_day_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='campaigngroup',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='membergroup',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timelineevent',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_context',
            field=models.CharField(choices=[('mundo', 'Mundo'), ('nossas', 'Nossas')], default='mundo', max_length=6, verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, verbose_name='Mês'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('mobilization_id', 'site')},
        ),
    ]
