# Generated by Django 4.2 on 2024-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='columns',
        ),
        migrations.AlterField(
            model_name='grid',
            name='gap',
            field=models.IntegerField(default=1, help_text="Unidade de medida em 'rem'"),
        ),
    ]
