# Generated by Django 4.2 on 2024-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_remove_grid_columns_alter_grid_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
