# Generated by Django 3.2 on 2023-07-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('address_line', models.CharField(max_length=200, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(verbose_name='Valor')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Whatsapp')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicao.pollingplace')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('bio', models.TextField(verbose_name='Minibio')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.FileField(blank=True, null=True, upload_to='candidatos/fotos/', verbose_name='Foto')),
                ('video', models.FileField(blank=True, null=True, upload_to='candidatos/videos/', verbose_name='Video')),
                ('gender', models.CharField(choices=[('masculino', 'Male'), ('feminino', 'Female'), ('não binário', 'Nonbinary'), ('travesti', 'Travesti'), ('não declarado', 'No Answer')], max_length=20, verbose_name='Genero')),
                ('is_trans', models.BooleanField(default=False, verbose_name='Pessoa Trans?')),
                ('sexuality', models.CharField(choices=[('heterossexual', 'Heterossexual'), ('homossexual', 'Homossexual'), ('pansexual', 'Pansexual'), ('assexual', 'Assexual'), ('bissexual', 'Bissexual'), ('não declarada', 'No Answer')], max_length=20, verbose_name='Sexualidade')),
                ('race', models.CharField(choices=[('branca', 'White'), ('preta', 'Black'), ('amarela', 'Yellow'), ('indigena', 'Indigenous'), ('parda', 'Pardo'), ('não declarada', 'No Answer')], max_length=20, verbose_name='Raça')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('social_media', models.JSONField(blank=True, null=True, verbose_name='Redes sociais')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Numero do candidato')),
                ('is_reelection', models.BooleanField(default=False, verbose_name='Reeleição')),
                ('themes', models.ManyToManyField(to='eleicao.Theme')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicao.pollingplace')),
            ],
        ),
    ]
