# Generated by Django 3.2 on 2023-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Male'), ('feminino', 'Female'), ('não binário', 'Nonbinary'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'No Answer')], max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sexuality',
            field=models.CharField(choices=[('heterossexual', 'Heterossexual'), ('pansexual', 'Pansexual'), ('assexual', 'Assexual'), ('bissexual', 'Bissexual'), ('queer', 'Queer'), ('gay', 'Gay'), ('lesbica', 'Lesbica'), ('não declarada', 'No Answer')], max_length=20, verbose_name='Sexualidade'),
        ),
    ]
