# Generated by Django 3.2 on 2023-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Numero de voto'),
        ),
    ]
