# Generated by Django 3.2 on 2023-08-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_auto_20230821_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingplace',
            old_name='referente',
            new_name='reference',
        ),
    ]
