# Generated by Django 3.2 on 2023-08-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0004_alter_candidate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pollingplace',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pollingplace',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='pollingplace',
            name='state',
        ),
        migrations.AddField(
            model_name='candidate',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eleicao.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingplace',
            name='places',
            field=models.ManyToManyField(to='eleicao.Address'),
        ),
    ]
