# Generated by Django 3.2 on 2023-08-01 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0005_auto_20230801_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Quero receber atualizações da campanha e do NOSSAS.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='occupation',
            field=models.CharField(default='', max_length=100, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[], max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(choices=[], max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('FN', 'Fernando de Noronha'), ('GB', 'Guanabara'), ('GU', 'Guaporé'), ('IG', 'Iguaçu'), ('PP', 'Ponta Porã'), ('RB', 'Rio Branco')], max_length=2, verbose_name='Estado'),
        ),
    ]
