# Generated by Django 3.2 on 2023-08-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_eleicaocarousel'),
        ('eleicao', '0005_auto_20230821_1859'),
    ]

    operations = [
    ]
