# Generated by Django 3.2 on 2023-08-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0006_auto_20230801_2019'),
        ('eleicao', '0006_auto_20230801_2057'),
    ]

    operations = [
    ]
