# Generated by Django 3.2 on 2023-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0007_auto_20230801_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('indigena', 'Indigena'), ('parda', 'Parda'), ('não declarada', 'Não declarada')], max_length=20, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pollingplace',
            name='address_line',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
    ]
