# Generated by Django 3.2 on 2023-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0007_merge_0006_auto_20230801_2019_0006_auto_20230801_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
    ]
