# Generated by Django 3.2 on 2023-08-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0007_auto_20230801_2141'),
        ('eleicao', '0008_auto_20230801_2141'),
    ]

    operations = [
    ]
