# Generated by Django 3.2 on 2023-08-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0008_auto_20230802_1237'),
        ('eleicao', '0009_merge_0007_auto_20230801_2141_0008_auto_20230801_2141'),
    ]

    operations = [
    ]
