# Generated by Django 3.2 on 2023-08-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0010_merge_20230802_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=20, verbose_name='Genero'),
        ),
    ]
