# Generated by Django 3.2 on 2023-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0011_auto_20230824_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Seu link personalizado'),
        ),
    ]
