# Generated by Django 3.2 on 2023-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0012_alter_address_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='zone',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_reelection',
            field=models.BooleanField(default=False, verbose_name='Está se candidatando para reeleição?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_trans',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Se identifica como pessoa transgênero/transexual?'),
        ),
    ]
