# Generated by Django 3.2 on 2023-08-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0012_alter_address_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='zone',
        ),
    ]
