# Generated by Django 3.2 on 2023-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0012_alter_address_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='sexuality',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='themes',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Seu link personalizado'),
        ),
    ]
