# Generated by Django 3.2 on 2023-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0013_auto_20230807_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='themes',
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=80, verbose_name='Bairro onde se candidatou'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_reelection',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Está se candidatando para reeleição?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Número de voto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sexuality',
            field=models.CharField(choices=[('Heterossexual', 'Heterossexual'), ('Pansexual', 'Pansexual'), ('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Queer', 'Queer'), ('Gay', 'Gay'), ('Lésbica', 'Lesbica'), ('Não declarada', 'No Answer')], max_length=20, verbose_name='Sexualidade'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Seu link personalizado'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/videos/', verbose_name='Video'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
