# Generated by Django 3.2 on 2023-08-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0013_auto_20230809_1448'),
        ('eleicao', '0013_remove_candidate_zone'),
    ]

    operations = [
    ]
