# Generated by Django 3.2 on 2023-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0014_merge_20230809_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='candidate',
            name='social_media_2',
            field=models.CharField(max_length=100, null=True, verbose_name='URL da Rede Social'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='social_media',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, null=True, verbose_name='Rede social'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/videos/', verbose_name='Video'),
        ),
    ]
