# Generated by Django 3.2 on 2023-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0015_auto_20230809_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=80, verbose_name='Bairro onde se candidatou'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_reelection',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Está se candidatando para reeleição?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_trans',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Se identifica como pessoa transgênero/transexual?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Numero de voto'),
        ),
    ]
