# Generated by Django 3.2 on 2023-08-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0017_auto_20230814_1726'),
        ('eleicao', '0018_auto_20230814_1702'),
    ]

    operations = [
    ]
