# Generated by Django 3.2 on 2023-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0018_eleicaocandidatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleicaocandidatelist',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='eleicaocandidatelist',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Título'),
        ),
    ]
