# Generated by Django 3.2 on 2023-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0019_merge_0017_auto_20230814_1726_0018_auto_20230814_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('não binário', 'Não binário'), ('travesti', 'Travesti'), ('queer', 'Queer'), ('não declarado', 'Não declarado')], max_length=30, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, help_text='Envie uma foto horizontal com no mínimo 700 pixels de largura, nos formatos JPEG ou PNG, para garantir a melhor qualidade visual. 📸✨', null=True, upload_to='candidaturas/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('indigena', 'Indigena'), ('parda', 'Parda'), ('não declarada', 'Não declarada')], max_length=30, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('published', 'Publicado'), ('disabled', 'Desabilitado')], default='published', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video',
            field=models.FileField(blank=True, help_text='Carregue um vídeo de até 30 segundos na posição horizontal, escolhendo entre os formatos MP4, AVI ou MOV. 🎥📽️', null=True, upload_to='candidaturas/videos/', verbose_name='Video'),
        ),
    ]
