# Generated by Django 4.2 on 2024-09-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_partner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição'),
        ),
    ]
