# Generated by Django 4.2 on 2024-09-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='link',
        ),
    ]
